# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SigBus
                                 A QGIS plugin
 Análise de transporte público (GTFS + dados de demanda)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-12
        copyright            : (C) 2022 by Diego Camargo
        email                : diegocamargo.bft@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SigBus class from file SigBus.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .SigBus import SigBus
    return SigBus(iface)
