# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SigBusDialog
                                 A QGIS plugin
 Análise de transporte público (GTFS + dados de demanda)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-12
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Diego Camargo
        email                : diegocamargo.bft@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import csv
import io
import os
import sqlite3
import tempfile
import zipfile
from datetime import datetime
from zipfile import ZipFile

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtCore import QVariant
from qgis.PyQt.QtGui import QFont
from qgis.PyQt.QtWidgets import (
    QFileDialog,
    QWidget,
    QVBoxLayout,
    QLabel,
    QPushButton,
    QMessageBox,
    QComboBox,
)
from qgis.core import (
    Qgis,
    QgsApplication,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsCoordinateTransformContext,
    QgsCategorizedSymbolRenderer,
    QgsDistanceArea,
    QgsFeature,
    QgsField,
    QgsGeometry,
    QgsGraduatedSymbolRenderer,
    QgsLayerTreeLayer,
    QgsLineSymbol,
    QgsLayoutExporter,
    QgsLayerTree,
    QgsLayoutItemLabel,
    QgsLayoutItemLegend,
    QgsLayoutItemMap,
    QgsLayoutItemPage,
    QgsLayoutItemPicture,
    QgsLayoutItemScaleBar,
    QgsLayoutPoint,
    QgsLayoutSize,
    QgsMessageLog,
    QgsPointXY,
    QgsPrintLayout,
    QgsProject,
    QgsTask,
    QgsRendererCategory,
    QgsRendererRange,
    QgsUnitTypes,
    QgsVectorFileWriter,
    QgsVectorLayer,
)
from qgis.utils import iface
import processing as _processing

from .gtfs_reader import (
    ESSENTIAL_LAYERS,
    GtfsError,
    GtfsReader,
    create_join_indexes,
)
from .gtfs_edit_core import WorkingCopy
from . import gtfs_schema
from .gtfs_export import GtfsExporter

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'SigBus_dialog_base.ui'))

# --- Simbologia compartilhada -------------------------------------------
# Os dois mapas do relatório separam as variáveis: o mapa de Carregamento
# usa espessura graduada por passageiros_acum (cor única); o mapa de
# Clusters usa cor por cluster_id (espessura uniforme). Cada um tem uma
# legenda nativa e limpa, em vez de empilhar as duas variáveis numa linha só.
LOAD_COLOR = '#2B6CB0'            # azul fixo do mapa de carregamento
WIDTH_MIN, WIDTH_MAX = 0.4, 2.8  # espessura (mm) das classes de carga
N_LOAD_CLASSES = 5


def _load_breaks(values):
    """(lo, hi, width) de N_LOAD_CLASSES classes de Intervalo Igual sobre
    `values` (lista de passageiros_acum). Min/max calculados na própria lista
    — minimumValue/maximumValue do provedor de memória pode retornar None."""
    v_min = min(values) if values else 0.0
    v_max = max(values) if values else 1.0
    if v_max <= v_min:
        v_max = v_min + 1
    step = (v_max - v_min) / N_LOAD_CLASSES
    breaks = []
    for i in range(N_LOAD_CLASSES):
        lo = v_min + i * step
        hi = v_min + (i + 1) * step if i < N_LOAD_CLASSES - 1 else v_max
        width = WIDTH_MIN + (WIDTH_MAX - WIDTH_MIN) * i / (N_LOAD_CLASSES - 1)
        breaks.append((lo, hi, round(width, 2)))
    return breaks


def make_load_renderer(values):
    """Renderer graduado por passageiros_acum: espessura crescente, cor única.
    A legenda mostra as 5 classes de carga (graduação visível)."""
    ranges = []
    for lo, hi, width in _load_breaks(values):
        sym = QgsLineSymbol.createSimple({
            'color':     LOAD_COLOR,
            'width':     '{:.2f}'.format(width),
            'capstyle':  'round',
            'joinstyle': 'round',
        })
        ranges.append(QgsRendererRange(
            lo, hi, sym, '{:.0f} – {:.0f}'.format(lo, hi)))
    return QgsGraduatedSymbolRenderer('passageiros_acum', ranges)


def make_cluster_renderer(color_map):
    """Renderer categorizado por cluster_id: cor por cluster, espessura
    uniforme. A legenda (ou o gráfico de barras) mostra as cores 1:1."""
    cats = []
    for lbl, color in color_map.items():
        sym = QgsLineSymbol.createSimple({
            'color':     color,
            'width':     '1.2',
            'capstyle':  'round',
            'joinstyle': 'round',
        })
        cats.append(QgsRendererCategory(lbl, sym, lbl))
    return QgsCategorizedSymbolRenderer('cluster_id', cats)


class _HorariosTask(QgsTask):
    """Monta a camada de pontos de horários por parada para uma LINHA.

    A linha é identificada por route_short_name (ex. '101'), porque o
    shape_id do GTFS da BHTrans é numérico e sem significado para o usuário.
    O join é: routes (route_short_name → route_id) ⋈ trips ⋈ stop_times.

    Estratégia:
    - stop_times × trips: lidos via sqlite3 (tabelas sem geometria — seguro).
    - Coordenadas das paradas: lidas da camada stops via OGR (tabela pequena).
    - Resultado: camada de pontos em memória — abre instantaneamente."""

    def __init__(self, gpkg_path, route_name):
        super().__init__('Carregando horários', QgsTask.CanCancel)
        self.gpkg_path = gpkg_path
        self.route_name = str(route_name)
        # (stop_id, seq, arr, dep, trip_id, route_id, shape_id, dir, svc, nome, wkt)
        self._rows = []
        self.error = None

    def run(self):
        try:
            # Coordenadas e nomes das paradas (tabela pequena, lida via OGR)
            stops_vlayer = QgsVectorLayer(
                self.gpkg_path + '|layername=stops', '_hp_stops', 'ogr')
            stop_data = {}  # stop_id -> (stop_name, wkt)
            for feat in stops_vlayer.getFeatures():
                stop_data[str(feat['stop_id'])] = (
                    str(feat['stop_name'] or ''),
                    feat.geometry().asWkt(),
                )

            with sqlite3.connect(self.gpkg_path) as conn:
                # Linha → route_id
                row = conn.execute(
                    "SELECT route_id FROM routes WHERE route_short_name=?",
                    (self.route_name,)).fetchone()
                if not row:
                    self.error = ("Linha '{}' não encontrada em routes "
                                  "(use route_short_name).".format(self.route_name))
                    return False
                route_id = row[0]

                rows = conn.execute(
                    "SELECT st.stop_id, st.stop_sequence, "
                    "st.arrival_time, st.departure_time, "
                    "t.trip_id, t.shape_id, t.direction_id, t.service_id "
                    "FROM stop_times AS st "
                    "JOIN trips AS t ON st.trip_id = t.trip_id "
                    "WHERE t.route_id = ?",
                    (route_id,)).fetchall()

            self.route_id = route_id
            for r in rows:
                stop_id = str(r[0])
                if stop_id not in stop_data:
                    continue
                stop_name, wkt = stop_data[stop_id]
                self._rows.append((
                    stop_id, r[1], r[2], r[3], r[4], r[5], r[6], r[7],
                    stop_name, wkt,
                ))
        except Exception as e:  # noqa: BLE001
            self.error = str(e)
            return False
        return True

    def finished(self, result):
        project = QgsProject.instance()
        for old in project.mapLayersByName('horarios_paradas'):
            project.removeMapLayer(old.id())

        if not result:
            iface.messageBar().pushMessage(
                "Erro",
                "Falha ao carregar horários: {}".format(
                    self.error or "tarefa interrompida."),
                level=Qgis.Critical, duration=10)
            return

        mem = QgsVectorLayer("Point?crs=EPSG:4326", "horarios_paradas", "memory")
        provider = mem.dataProvider()
        provider.addAttributes([
            QgsField('stop_id',        QVariant.String),
            QgsField('stop_sequence',  QVariant.String),
            QgsField('arrival_time',   QVariant.String),
            QgsField('departure_time', QVariant.String),
            QgsField('trip_id',        QVariant.String),
            QgsField('shape_id',       QVariant.String),
            QgsField('direction_id',   QVariant.String),
            QgsField('service_id',     QVariant.String),
            QgsField('stop_name',      QVariant.String),
            QgsField('linha',          QVariant.String),
        ])
        mem.updateFields()

        fields = mem.fields()
        idx = {f.name(): fields.indexFromName(f.name()) for f in fields}

        feats = []
        for (stop_id, seq, arr, dep, trip_id, shape_id, direction, svc,
             stop_name, wkt) in self._rows:
            feat = QgsFeature(fields)
            feat.setGeometry(QgsGeometry.fromWkt(wkt))
            attrs = feat.attributes()
            attrs[idx['stop_id']]        = stop_id
            attrs[idx['stop_sequence']]  = seq
            attrs[idx['arrival_time']]   = arr
            attrs[idx['departure_time']] = dep
            attrs[idx['trip_id']]        = trip_id
            attrs[idx['shape_id']]       = shape_id
            attrs[idx['direction_id']]   = direction
            attrs[idx['service_id']]     = svc
            attrs[idx['stop_name']]      = stop_name
            attrs[idx['linha']]          = self.route_name
            feat.setAttributes(attrs)
            feats.append(feat)

        provider.addFeatures(feats)
        mem.updateExtents()

        if mem.isValid() and mem.featureCount() > 0:
            project.addMapLayer(mem)
            iface.messageBar().pushMessage(
                "Info",
                "Horários carregados: {} registros para a linha {}.".format(
                    mem.featureCount(), self.route_name),
                level=Qgis.Info, duration=8)
        else:
            iface.messageBar().pushMessage(
                "Aviso",
                "Nenhum horário encontrado para a linha {}.".format(
                    self.route_name),
                level=Qgis.Warning, duration=8)


class _GtfsLoadTask(QgsTask):
    """Tarefa de fundo que carrega um GTFS num GeoPackage.

    O trabalho pesado de I/O (descompactar + gravar tabelas) roda em run(),
    fora da thread da GUI. A adição das camadas ao projeto acontece em
    finished(), que o QGIS executa na thread principal — único lugar seguro
    para mexer em QgsProject."""

    def __init__(self, gtfs_path, gpkg_path):
        super().__init__('Carregando GTFS', QgsTask.CanCancel)
        self.gtfs_path = gtfs_path
        self.gpkg_path = gpkg_path
        self.reader = GtfsReader(gtfs_path)
        self.layer_names = []
        self.has_shapes = False
        self.error = None

    def run(self):
        try:
            self.setProgress(5)
            # Importa as tabelas (parte mais demorada: stop_times).
            self.layer_names = self.reader.write(self.gpkg_path)
            self.setProgress(75)
            # Constrói as linhas a partir de shapes_point.
            shapes = self.reader.build_shapes_line(self.gpkg_path)
            self.has_shapes = shapes is not None and shapes.isValid()
            self.setProgress(90)
            # Índices nas chaves de join, para a camada virtual ser rápida.
            create_join_indexes(self.gpkg_path)
            self.setProgress(100)
        except GtfsError as e:
            self.error = str(e)
            return False
        except Exception as e:  # noqa: BLE001 — reporta qualquer falha à GUI
            self.error = str(e)
            return False
        finally:
            self.reader.cleanup()
        return True

    def finished(self, result):
        if not result:
            msg = self.error or "tarefa cancelada ou interrompida."
            iface.messageBar().pushMessage(
                "Erro", "Falha ao carregar o GTFS: {}".format(msg),
                level=Qgis.Critical, duration=10)
            return

        # Carrega apenas as camadas essenciais como camadas de mapa. As
        # demais tabelas (stop_times, fare_*, agency...) permanecem no
        # GeoPackage para alimentar os joins.
        for name in self.layer_names:
            if name not in ESSENTIAL_LAYERS:
                continue
            layer = QgsVectorLayer(
                self.gpkg_path + '|layername=' + name, name, 'ogr')
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)

        # Camada de linhas (shapes) construída a partir de shapes_point.
        if self.has_shapes:
            shapes_layer = QgsVectorLayer(
                self.gpkg_path + '|layername=shapes', 'shapes', 'ogr')
            if shapes_layer.isValid():
                QgsProject.instance().addMapLayer(shapes_layer)

        iface.messageBar().pushMessage(
            "Info",
            "GTFS carregado em '{}'. Escolha uma linha e clique em "
            "'Filtrar dados' para ver os horários por parada.".format(
                os.path.basename(self.gpkg_path)),
            level=Qgis.Info, duration=12)


class _DemandLoadTask(QgsTask):
    """Tarefa de fundo que carrega o CSV de demanda num GeoPackage e calcula
    o campo shape_id.

    O cálculo do shape_id é feito por um único UPDATE em SQL (o GeoPackage é
    SQLite), em vez do loop de edição feição-a-feição do código original —
    que rodava na thread da GUI e travava com muitos registros."""

    def __init__(self, data_path, gpkg_path):
        super().__init__('Carregando dados de demanda', QgsTask.CanCancel)
        self.data_path = data_path
        self.gpkg_path = gpkg_path
        self.error = None

    def run(self):
        try:
            self.setProgress(10)
            uri = (
                "file:///" + self.data_path +
                "?encoding={}&type=csv&delimiter={}&xField={}&yField={}"
                "&geomType=point&crs={}&spatialIndex=yes".format(
                    'windows-1252', ';', 'X', 'Y', 'EPSG:31983'))
            vlayer = QgsVectorLayer(uri, 'dados_demanda', 'delimitedtext')
            if not vlayer.isValid():
                self.error = ("CSV de demanda inválido (verifique as colunas "
                              "X/Y, o separador ';' e o encoding).")
                return False

            field_names = [f.name() for f in vlayer.fields()]
            for needed in ('LINHA', 'SUBLINHA', 'PC'):
                if needed not in field_names:
                    self.error = ("Coluna '{}' ausente no CSV de demanda."
                                  .format(needed))
                    return False

            # Não calculamos mais um shape_id sintético: o GTFS da BHTrans
            # usa shape_id numérico, sem relação com LINHA/SUBLINHA/PC. A
            # ligação demanda→GTFS é feita por LINHA = routes.route_short_name
            # (ver _AlocacaoTask / filterClicked). A coluna LINHA do CSV é a
            # chave; nada a derivar aqui.

            self.setProgress(50)
            opt = QgsVectorFileWriter.SaveVectorOptions()
            opt.driverName = 'GPKG'
            opt.layerName = 'dados_demanda'
            opt.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
            res = QgsVectorFileWriter.writeAsVectorFormatV3(
                vlayer, self.gpkg_path, QgsCoordinateTransformContext(), opt)
            if res[0] != QgsVectorFileWriter.NoError:
                self.error = "Falha ao gravar dados_demanda: {}".format(res[1])
                return False
            self.setProgress(100)
        except Exception as e:  # noqa: BLE001 — reporta qualquer falha à GUI
            self.error = str(e)
            return False
        return True

    def finished(self, result):
        if not result:
            iface.messageBar().pushMessage(
                "Erro",
                "Falha ao carregar a demanda: {}".format(
                    self.error or "tarefa interrompida."),
                level=Qgis.Critical, duration=10)
            return
        iface.addVectorLayer(
            self.gpkg_path + '|layername=dados_demanda',
            'dados_demanda', 'ogr')
        iface.messageBar().pushMessage(
            "Info", "Dados de demanda carregados (chave de ligação: LINHA).",
            level=Qgis.Info, duration=10)


class _AlocacaoTask(QgsTask):
    """Aloca embarques da demanda nos tramos de uma LINHA, por sentido.

    A linha é identificada por route_short_name (ex. '101'). Para cada
    sentido, usa o shape DOMINANTE (com mais viagens), pega a sequência de
    paradas desse shape e aloca os embarques (do CSV, filtrados por
    LINHA + PC) ao stop mais próximo. PC=1 → ida (direction_id 0),
    PC=2 → volta (direction_id 1).

    Saída: camada 'tramos_demanda' com segmentos por sentido e campo
    'embarques' pronto para simbologia graduada."""

    _PC_TO_DIR = {'1': '0', '2': '1'}       # PC (demanda) → direction_id (GTFS)
    _DIR_LABEL = {'0': 'ida', '1': 'volta'}

    def __init__(self, gpkg_path, route_name, hora=None, demand_gpkg=None):
        super().__init__('Alocando demanda', QgsTask.CanCancel)
        self.gpkg_path = gpkg_path          # GTFS (routes/trips/stops)
        self.demand_gpkg = demand_gpkg or gpkg_path   # dados_demanda
        self.route_name = str(route_name)
        # hora=None → Total geral; hora=int(0..23) → coluna horária
        self.hora = hora
        # (wkt, seq_a, sid_a, nome_a, sid_b, nome_b, emb, pc, sentido)
        self._segments = []
        self._avisos = []
        self.error = None

    def _find_emb_col(self, conn):
        """Devolve o nome real da coluna de embarques em dados_demanda."""
        cols = [row[1] for row in conn.execute("PRAGMA table_info(dados_demanda)")]
        if self.hora is None:
            for c in cols:
                if 'total' in c.lower() and 'geral' in c.lower():
                    return c
            return None
        hora_str = str(self.hora)
        return hora_str if hora_str in cols else None

    def _load_shape_geom(self, shape_id):
        """Geometria (LineString) do shape_id na camada 'shapes' do GeoPackage.
        Retorna QgsGeometry de parte única, ou None se ausente/inválido. Linhas
        multipartes são fundidas (mergeLines) para permitir curveSubstring."""
        lyr = QgsVectorLayer(
            self.gpkg_path + '|layername=shapes', '_aloc_shp', 'ogr')
        if not lyr.isValid():
            return None
        sid = str(shape_id).replace("'", "''")
        lyr.setSubsetString("shape_id = '{}'".format(sid))
        for feat in lyr.getFeatures():
            g = feat.geometry()
            if g is None or g.isEmpty():
                continue
            geom = QgsGeometry(g)          # cópia
            if geom.isMultipart():
                merged = geom.mergeLines()
                if merged and not merged.isEmpty() and not merged.isMultipart():
                    geom = merged
            return geom
        return None

    @staticmethod
    def _segment_wkt(shape_geom, lon_a, lat_a, lon_b, lat_b):
        """WKT do trecho do shape entre as projeções dos dois stops na linha.
        Fallback para a reta A→B se o shape faltar ou a projeção falhar
        (ex.: shape multiparte sem curveSubstring)."""
        straight = "LINESTRING({} {}, {} {})".format(lon_a, lat_a, lon_b, lat_b)
        if shape_geom is None or shape_geom.isEmpty() or shape_geom.isMultipart():
            return straight
        try:
            da = shape_geom.lineLocatePoint(
                QgsGeometry.fromPointXY(QgsPointXY(lon_a, lat_a)))
            db = shape_geom.lineLocatePoint(
                QgsGeometry.fromPointXY(QgsPointXY(lon_b, lat_b)))
            if da < 0 or db < 0:
                return straight
            if db < da:
                da, db = db, da
            sub = shape_geom.constGet().curveSubstring(da, db)
            if sub is None:
                return straight
            sub_geom = QgsGeometry(sub)
            if sub_geom.isEmpty() or sub_geom.length() <= 0:
                return straight
            return sub_geom.asWkt()
        except Exception:   # noqa: BLE001
            return straight

    def _shapes_in_window(self, conn, route_id, direction):
        """[(shape_id, n_viagens)] do sentido na janela (hora ou total), desc."""
        if self.hora is not None:
            rows = conn.execute(
                "SELECT t.shape_id, COUNT(*) c FROM trips t "
                "JOIN stop_times st ON st.trip_id=t.trip_id "
                "WHERE t.route_id=? AND t.direction_id=? "
                "  AND CAST(st.stop_sequence AS INTEGER)=("
                "    SELECT MIN(CAST(ss.stop_sequence AS INTEGER)) "
                "    FROM stop_times ss WHERE ss.trip_id=t.trip_id) "
                "  AND CAST(SUBSTR(st.departure_time,1,2) AS INTEGER)=? "
                "GROUP BY t.shape_id ORDER BY c DESC",
                (route_id, direction, self.hora)).fetchall()
        else:
            rows = conn.execute(
                "SELECT shape_id, COUNT(*) c FROM trips "
                "WHERE route_id=? AND direction_id=? "
                "GROUP BY shape_id ORDER BY c DESC",
                (route_id, direction)).fetchall()
        return [(str(r[0]), int(r[1])) for r in rows]

    @staticmethod
    def _shape_stop_ids(conn, shape_id):
        """Conjunto de stop_ids servidos por uma viagem do shape."""
        trip = conn.execute(
            "SELECT trip_id FROM trips WHERE shape_id=? LIMIT 1",
            (shape_id,)).fetchone()
        if not trip:
            return set()
        rows = conn.execute(
            "SELECT stop_id FROM stop_times WHERE trip_id=?", (trip[0],)).fetchall()
        return {str(r[0]) for r in rows}

    def _log_shape_diff(self, conn, route_id, direction, dominant_id, sent_lbl):
        """Loga, por shape do sentido: viagens, nº de paradas, comprimento (km)
        e — para os alternativos — quantas paradas eles têm que o dominante NÃO
        cobre. Se esse número for 0, a simplificação 'só dominante' não perde
        demanda (alternativo é subconjunto); se >0, há divergência real."""
        da = QgsDistanceArea()
        da.setSourceCrs(QgsCoordinateReferenceSystem('EPSG:4326'),
                        QgsCoordinateTransformContext())
        da.setEllipsoid('WGS84')

        dom_stops = self._shape_stop_ids(conn, dominant_id)
        for sid, n_trips in self._shapes_in_window(conn, route_id, direction):
            geom = self._load_shape_geom(sid)
            length_km = (da.measureLength(geom) / 1000.0
                         if geom and not geom.isEmpty() else 0.0)
            stops = self._shape_stop_ids(conn, sid)
            if sid == dominant_id:
                extra_msg = ' [DOMINANTE]'
            else:
                extra = stops - dom_stops
                extra_msg = ' [alt] — {} parada(s) fora do dominante'.format(
                    len(extra))
            QgsMessageLog.logMessage(
                "  {} shape {}: {} viagens, {} paradas, {:.1f} km{}".format(
                    sent_lbl, sid, n_trips, len(stops), length_km, extra_msg),
                'SIG-Bus', Qgis.Info)

    # ------------------------------------------------------------------
    def run(self):
        try:
            # 1. Coordenadas e nomes dos stops (OGR — tabela pequena) ----
            stops_vlayer = QgsVectorLayer(
                self.gpkg_path + '|layername=stops', '_aloc_s', 'ogr')
            stop_info = {}   # stop_id -> (nome, lat, lon)
            for feat in stops_vlayer.getFeatures():
                pt = feat.geometry().asPoint()
                stop_info[str(feat['stop_id'])] = (
                    str(feat['stop_name'] or ''), pt.y(), pt.x())

            # 2. Lê demanda de dados_demanda (arquivo separado ou mesmo gpkg)
            demanda_por_pc = {'1': [], '2': []}
            with sqlite3.connect(self.demand_gpkg) as dconn:
                tables = {r[0] for r in dconn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'")}
                if 'dados_demanda' not in tables:
                    self.error = ("Tabela 'dados_demanda' não encontrada em "
                                  "'{}'.".format(os.path.basename(self.demand_gpkg)))
                    return False

                emb_col = self._find_emb_col(dconn)
                if emb_col is None:
                    label = 'Total geral' if self.hora is None else str(self.hora)
                    self.error = ("Coluna '{}' não encontrada em dados_demanda."
                                  .format(label))
                    return False

                sql = ('SELECT "PC", "Latitude.WGS84", "Longitude.WGS84", "{}" '
                       'FROM dados_demanda WHERE "LINHA" = ?'.format(emb_col))
                for r in dconn.execute(sql, (self.route_name,)):
                    pc = str(r[0]).strip() if r[0] else ''
                    if pc not in demanda_por_pc:
                        continue
                    try:
                        lat = float(str(r[1]).strip())
                        lon = float(str(r[2]).strip())
                        emb = int(float(str(r[3] or 0)))
                    except (ValueError, TypeError):
                        continue
                    demanda_por_pc[pc].append((lat, lon, emb))

            if not any(demanda_por_pc.values()):
                self.error = ("Nenhuma demanda para a linha '{}' em dados_demanda."
                              .format(self.route_name))
                return False

            # 3. Queries GTFS (route_id, shape dominante, sequência de paradas)
            with sqlite3.connect(self.gpkg_path) as conn:
                row = conn.execute(
                    "SELECT route_id FROM routes WHERE route_short_name=?",
                    (self.route_name,)).fetchone()
                if not row:
                    self.error = ("Linha '{}' não encontrada em routes."
                                  .format(self.route_name))
                    return False
                route_id = row[0]

                # Processa cada sentido com demanda --------------------
                for pc, pts in demanda_por_pc.items():
                    if not pts:
                        continue
                    direction = self._PC_TO_DIR[pc]

                    # Shape dominante + contagem de viagens ----------
                    # Quando uma hora específica está selecionada, restringe
                    # às viagens que *iniciam* nessa hora (departure_time da
                    # primeira parada). Isso amarra a demanda horária às
                    # viagens que realmente serviram aquela janela de tempo.
                    if self.hora is not None:
                        shp = conn.execute(
                            "SELECT t.shape_id, COUNT(*) c "
                            "FROM trips t "
                            "JOIN stop_times st ON st.trip_id = t.trip_id "
                            "WHERE t.route_id = ? AND t.direction_id = ? "
                            "  AND CAST(st.stop_sequence AS INTEGER) = ("
                            "    SELECT MIN(CAST(ss.stop_sequence AS INTEGER))"
                            "    FROM stop_times ss WHERE ss.trip_id = t.trip_id"
                            "  )"
                            "  AND CAST(SUBSTR(st.departure_time,1,2) AS INTEGER) = ? "
                            "GROUP BY t.shape_id ORDER BY c DESC LIMIT 1",
                            (route_id, direction, self.hora)).fetchone()
                        if shp:
                            n_viagens = shp[1]
                        else:
                            # Sem viagens nessa hora: usa shape geral como fallback
                            shp = conn.execute(
                                "SELECT shape_id, COUNT(*) c FROM trips "
                                "WHERE route_id=? AND direction_id=? "
                                "GROUP BY shape_id ORDER BY c DESC LIMIT 1",
                                (route_id, direction)).fetchone()
                            n_viagens = 0
                            self._avisos.append(
                                "PC={}: nenhuma viagem iniciando às {:02d}h; "
                                "usando shape geral.".format(pc, self.hora))
                    else:
                        shp = conn.execute(
                            "SELECT shape_id, COUNT(*) c FROM trips "
                            "WHERE route_id=? AND direction_id=? "
                            "GROUP BY shape_id ORDER BY c DESC LIMIT 1",
                            (route_id, direction)).fetchone()
                        n_viagens = shp[1] if shp else 0

                    if not shp:
                        self._avisos.append(
                            "PC={} (sentido {}) sem viagens no GTFS."
                            .format(pc, self._DIR_LABEL.get(direction, direction)))
                        continue
                    shape_id = shp[0]
                    shape_geom = self._load_shape_geom(shape_id)

                    # Diagnóstico: quantos shapes/viagens distintos esse sentido
                    # tem na janela. Vários shapes → o traçado mostrado (dominante)
                    # cobre só parte das viagens; pode explicar 'sobreposição'.
                    if self.hora is not None:
                        diag = conn.execute(
                            "SELECT COUNT(DISTINCT t.shape_id), COUNT(*) "
                            "FROM trips t JOIN stop_times st ON st.trip_id=t.trip_id "
                            "WHERE t.route_id=? AND t.direction_id=? "
                            "  AND CAST(st.stop_sequence AS INTEGER)=("
                            "    SELECT MIN(CAST(ss.stop_sequence AS INTEGER)) "
                            "    FROM stop_times ss WHERE ss.trip_id=t.trip_id) "
                            "  AND CAST(SUBSTR(st.departure_time,1,2) AS INTEGER)=?",
                            (route_id, direction, self.hora)).fetchone()
                    else:
                        diag = conn.execute(
                            "SELECT COUNT(DISTINCT shape_id), COUNT(*) FROM trips "
                            "WHERE route_id=? AND direction_id=?",
                            (route_id, direction)).fetchone()
                    n_shapes = diag[0] if diag else 0
                    n_trips_total = diag[1] if diag else 0
                    sent_lbl = self._DIR_LABEL.get(direction, direction)
                    QgsMessageLog.logMessage(
                        "Linha {} sentido {} ({}): {} shape(s) distinto(s), "
                        "{} viagem(ns); usando shape dominante {} ({} viagens)."
                        .format(self.route_name, sent_lbl,
                                'hora {:02d}h'.format(self.hora)
                                if self.hora is not None else 'total',
                                n_shapes, n_trips_total, shape_id, n_viagens),
                        'SIG-Bus', Qgis.Info)
                    if n_shapes > 1:
                        self._avisos.append(
                            "PC={} (sentido {}): {} traçados distintos na janela; "
                            "mostrando só o dominante.".format(pc, sent_lbl, n_shapes))
                        # Detalha cada shape para decidir se a simplificação perde demanda.
                        self._log_shape_diff(conn, route_id, direction,
                                             shape_id, sent_lbl)

                    # Uma viagem desse shape → sequência de paradas
                    trip = conn.execute(
                        "SELECT trip_id FROM trips WHERE shape_id=? LIMIT 1",
                        (shape_id,)).fetchone()
                    stop_rows = conn.execute(
                        "SELECT stop_id, stop_sequence FROM stop_times "
                        "WHERE trip_id=? ORDER BY CAST(stop_sequence AS INTEGER)",
                        (trip[0],)).fetchall()

                    route_stops = []
                    for sid, seq in stop_rows:
                        info = stop_info.get(str(sid))
                        if not info:
                            continue
                        nome, lat, lon = info
                        try:
                            seq_i = int(seq)
                        except (TypeError, ValueError):
                            seq_i = 0
                        route_stops.append((seq_i, str(sid), nome, lat, lon))
                    route_stops.sort(key=lambda x: x[0])
                    if len(route_stops) < 2:
                        self._avisos.append(
                            "PC={}: menos de 2 paradas no shape {}."
                            .format(pc, shape_id))
                        continue

                    # Spatial join por menor distância lat/lon
                    stop_demand = {s[1]: 0 for s in route_stops}
                    for dlat, dlon, emb in pts:
                        nearest = min(
                            route_stops,
                            key=lambda s: (dlat - s[3])**2 + (dlon - s[4])**2)
                        stop_demand[nearest[1]] += emb

                    # Segmentos entre stops consecutivos, com passageiros acumulados.
                    # passageiros_acum[i] = soma dos embarques em todos os stops
                    # até o stop de partida do segmento i — representa a carga
                    # real do ônibus naquele tramo (assumindo sem descidas).
                    sentido = self._DIR_LABEL.get(direction, direction)
                    acum = 0
                    for i in range(len(route_stops) - 1):
                        seq_a, sid_a, nome_a, lat_a, lon_a = route_stops[i]
                        _sb, sid_b, nome_b, lat_b, lon_b = route_stops[i + 1]
                        emb_a = stop_demand[sid_a]
                        acum += emb_a
                        # Trecho do shape entre os stops (cai na reta se faltar)
                        wkt = self._segment_wkt(
                            shape_geom, lon_a, lat_a, lon_b, lat_b)
                        self._segments.append((
                            wkt, seq_a, sid_a, nome_a, sid_b, nome_b,
                            emb_a, acum, pc, sentido, n_viagens))

            if not self._segments:
                self.error = ("Nenhum tramo gerado para a linha '{}'. {}"
                              .format(self.route_name, ' '.join(self._avisos)))
                return False

        except Exception as e:   # noqa: BLE001
            self.error = str(e)
            return False
        return True

    # ------------------------------------------------------------------
    def finished(self, result):
        project = QgsProject.instance()
        for old in project.mapLayersByName('tramos_demanda'):
            project.removeMapLayer(old.id())

        if not result:
            iface.messageBar().pushMessage(
                "Erro",
                "Falha na alocação: {}".format(self.error or "cancelada."),
                level=Qgis.Critical, duration=10)
            return

        mem = QgsVectorLayer("LineString?crs=EPSG:4326",
                             "tramos_demanda", "memory")
        prov = mem.dataProvider()
        prov.addAttributes([
            QgsField('seq_from',          QVariant.Int),
            QgsField('stop_id_from',      QVariant.String),
            QgsField('stop_name_from',    QVariant.String),
            QgsField('stop_id_to',        QVariant.String),
            QgsField('stop_name_to',      QVariant.String),
            QgsField('embarques',         QVariant.Int),
            QgsField('passageiros_acum',  QVariant.Int),
            QgsField('pc',                QVariant.String),
            QgsField('sentido',           QVariant.String),
            QgsField('linha',             QVariant.String),
            QgsField('hora',              QVariant.String),
            QgsField('n_viagens',         QVariant.Int),
        ])
        mem.updateFields()
        fields = mem.fields()
        idx = {f.name(): fields.indexFromName(f.name()) for f in fields}

        hora_label = 'Total' if self.hora is None else '{:02d}h'.format(self.hora)
        feats = []
        for (wkt, seq_a, sid_a, nome_a, sid_b, nome_b,
             emb, acum, pc, sentido, n_viagens) in self._segments:
            feat = QgsFeature(fields)
            feat.setGeometry(QgsGeometry.fromWkt(wkt))
            attrs = feat.attributes()
            attrs[idx['seq_from']]         = seq_a
            attrs[idx['stop_id_from']]     = sid_a
            attrs[idx['stop_name_from']]   = nome_a
            attrs[idx['stop_id_to']]       = sid_b
            attrs[idx['stop_name_to']]     = nome_b
            attrs[idx['embarques']]        = emb
            attrs[idx['passageiros_acum']] = acum
            attrs[idx['pc']]               = pc
            attrs[idx['sentido']]          = sentido
            attrs[idx['linha']]            = self.route_name
            attrs[idx['hora']]             = hora_label
            attrs[idx['n_viagens']]        = n_viagens
            feat.setAttributes(attrs)
            feats.append(feat)

        prov.addFeatures(feats)
        mem.updateExtents()

        if mem.isValid() and mem.featureCount() > 0:
            project.addMapLayer(mem)

            # Simbologia graduada por passageiros_acum (mapa de carregamento):
            # espessura crescente, cor única. Min/max vêm de self._segments.
            try:
                acum_vals = [s[7] for s in self._segments]
                mem.setRenderer(make_load_renderer(acum_vals))
                iface.layerTreeView().refreshLayerSymbology(mem.id())
            except Exception as _e:
                QgsMessageLog.logMessage(
                    'Simbologia graduada falhou: {}'.format(_e),
                    'SIG-Bus', Qgis.Warning)

            total_emb = sum(s[6] for s in self._segments)
            # Carga máxima = maior passageiros_acum entre todos os tramos
            carga_max = max(s[7] for s in self._segments)
            hora_label = 'Total' if self.hora is None else '{:02d}h'.format(self.hora)
            # Viagens por sentido (cada sentido pode ter valor diferente)
            viagens_por_pc = {}
            for s in self._segments:
                viagens_por_pc[s[8]] = s[10]  # pc -> n_viagens
            n_msg = ', '.join(
                '{} viagens sentido {}'.format(v, self._DIR_LABEL.get(self._PC_TO_DIR.get(p, p), p))
                for p, v in sorted(viagens_por_pc.items()) if v > 0)
            msg = ("{} tramos — {} embarques — carga máx. {} pax/tramo"
                   " — linha {} ({}).".format(
                       mem.featureCount(), total_emb, carga_max,
                       self.route_name, hora_label))
            if n_msg:
                msg += " GTFS: {}.".format(n_msg)
            if self._avisos:
                msg += " Avisos: " + ' '.join(self._avisos)
            iface.messageBar().pushMessage(
                "Info", msg, level=Qgis.Info, duration=12)
        else:
            iface.messageBar().pushMessage(
                "Aviso", "Nenhum tramo gerado.",
                level=Qgis.Warning, duration=8)


class SigBusDialog(QtWidgets.QDialog, FORM_CLASS):
    # Paleta qualitativa (até 10 cores distintas) compartilhada entre o mapa
    # (tramos_demanda categorizado por cluster) e o gráfico de barras, para
    # que cada cluster tenha a mesma cor nos dois.
    _CLUSTER_PALETTE = [
        '#E41A1C', '#377EB8', '#4DAF4A', '#984EA3', '#FF7F00',
        '#A65628', '#F781BF', '#808080', '#FFFF33', '#00CED1',
    ]

    @classmethod
    def _cluster_color_map(cls, assign_ida, assign_volta):
        """label de cluster → cor, usando o conjunto ordenado de todos os
        labels (ida ∪ volta) para garantir cores estáveis e iguais às do mapa."""
        labels = sorted(set(assign_ida.values()) | set(assign_volta.values()))
        pal = cls._CLUSTER_PALETTE
        return {lbl: pal[i % len(pal)] for i, lbl in enumerate(labels)}

    def __init__(self, parent=None):
        """Constructor."""
        super(SigBusDialog, self).__init__(parent)
        self.setupUi(self)
        self.gtfs_insert_button.clicked.connect(self.gtfsClicked)
        self.data_insert_button.clicked.connect(self.dataClicked)
        # O leitor de GTFS agora é embutido (gtfs_reader.py); não há mais
        # dependência do plugin externo GTFS Loader. O botão "Instalar GTFS
        # Loader" fica oculto e "Executar GTFS" carrega o feed diretamente.
        self.extrapackages.setVisible(False)
        self.button_gtfsgo.clicked.connect(self.loadGtfs)
        #Mudança de camada
        layer = self.mMapLayerComboBox.currentLayer()
        self.mMapLayerComboBox.layerChanged.connect(self.map_changed)
        self.mFieldComboBox.fieldChanged.connect(self.field_select)
        self.mFeaturePickerWidget.featureChanged.connect(self.field_select)
        #self.mFeatureListComboBox.setSourceLayer(self.mMapLayerComboBox.currentLayer())
        #Filter Button
        self.filterButton.clicked.connect(self.filterClicked)
        #self.mFeatureListComboBox.currentIndexChanged.connect(self.feature_select)
        #self.mFieldComboBox.indexChanged.connect(self.field_select)
        self.button_reconnect.clicked.connect(self.reconnectGpkg)
        self.button_alocar.clicked.connect(self.alocacaoClicked)
        self.button_relatorio.clicked.connect(self.relatorioClicked)

        # Seletor de hora: "Total geral" + horas 00h–23h
        self.combo_hora.addItem('Total geral')
        for h in range(24):
            self.combo_hora.addItem('{:02d}h'.format(h))

        # Botão "Diagrama de Blocos" — definido no .ui, na aba "Análise".
        self.button_diagrama.clicked.connect(self.diagramaClicked)

        # Inicialização da aba "Edição GTFS" (fatiada em código)
        tab = QWidget()
        layout = QVBoxLayout(tab)

        self.label_edit_status = QLabel("Nenhuma edição em andamento.")
        self.button_edit_enter = QPushButton("Entrar no modo edição")

        self.combo_edit_table = QComboBox()
        # ponytail: Filtra as tabelas para não oferecer paradas, shapes e stop_times na grade nativa
        tabelas_grade = [
            t for t in gtfs_schema.editable_tables()
            if t not in ('stops', 'shapes', 'stop_times')
        ]
        self.combo_edit_table.addItems(tabelas_grade)

        self.button_edit_open = QPushButton("Abrir para edição")
        self.button_edit_stops = QPushButton("Editar paradas no mapa")
        self.button_edit_export = QPushButton("Exportar .zip")
        self.button_edit_discard = QPushButton("Descartar edição")

        layout.addWidget(self.label_edit_status)
        layout.addWidget(self.button_edit_enter)
        layout.addWidget(self.combo_edit_table)
        layout.addWidget(self.button_edit_open)
        layout.addWidget(self.button_edit_stops)
        layout.addWidget(self.button_edit_export)
        layout.addWidget(self.button_edit_discard)
        layout.addStretch()

        self.tabWidget.addTab(tab, "Edição GTFS")

        self._working_copy = None

        # Conexões da Edição GTFS
        self.button_edit_enter.clicked.connect(self.editEnterClicked)
        self.button_edit_open.clicked.connect(self.editOpenClicked)
        self.button_edit_stops.clicked.connect(self.editStopsClicked)
        self.button_edit_export.clicked.connect(self.exportClicked)
        self.button_edit_discard.clicked.connect(self.editDiscardClicked)

        self._refresh_edit_status()

    def field_select(self):
        #field = self.mFieldComboBox.fields()
        layer = self.mMapLayerComboBox.currentLayer()
        field = self.mFieldComboBox.currentField()
        self.mFieldComboBox.setField(field)
        picker = self.mFeaturePickerWidget
        picker.setLayer(layer)
        picker.setDisplayExpression(field)
        feature = picker.feature()
        #print(feature[1])

        #Solução encontrada. Link para ajuda abaixo
        #https://qgis.org/pyqgis/master/core/QgsFeature.html#qgis.core.QgsFeature
        #https://gis.stackexchange.com/questions/409517/database-form-as-qgis-plugin-with-pyqgis-and-qtdesigner
        #Está saindo o número da posição do dado, precisa transformar no próprio dado. Ou não... Na verdade precisa
        #o próximo passo
        #self.mFeatureListComboBox.setDisplayExpression(field)
    #https://gis.stackexchange.com/questions/409517/database-form-as-qgis-plugin-with-pyqgis-and-qtdesigner

    def filterClicked(self):
        """Filtra pela LINHA escolhida (route_short_name).

        Espera-se que o usuário selecione a camada 'routes' e o campo
        'route_short_name' (ex.: '101'). A partir daí: destaca o traçado na
        camada 'shapes', filtra a demanda por LINHA e carrega os horários."""
        field = self.mFieldComboBox.currentField()
        feature = self.mFeaturePickerWidget.feature()
        if not feature.isValid() or not field:
            iface.messageBar().pushMessage(
                "Aviso", "Escolha uma linha antes de filtrar.",
                level=Qgis.Warning, duration=8)
            return
        value = feature[field]
        if value is None:
            return
        route_name = str(value).strip()

        gpkg = self._resolve_gpkg()
        if not gpkg:
            iface.messageBar().pushMessage(
                "Aviso",
                "GeoPackage não encontrado. Use 'Reconectar GeoPackage' "
                "para localizá-lo.",
                level=Qgis.Warning, duration=8)
            return

        # Resolve os shape_ids da linha (route_short_name → route_id → shapes)
        shape_ids = []
        try:
            with sqlite3.connect(gpkg) as conn:
                r = conn.execute(
                    "SELECT route_id FROM routes WHERE route_short_name=?",
                    (route_name,)).fetchone()
                if r:
                    shape_ids = [str(x[0]) for x in conn.execute(
                        "SELECT DISTINCT shape_id FROM trips WHERE route_id=?",
                        (r[0],)).fetchall() if x[0] is not None]
        except sqlite3.Error:
            pass

        # Destaca o traçado da linha na camada 'shapes'
        shapes_layers = QgsProject.instance().mapLayersByName('shapes')
        if shapes_layers and shape_ids:
            quoted = ", ".join(
                "'{}'".format(s.replace("'", "''")) for s in shape_ids)
            shapes_layers[0].setSubsetString(
                "shape_id IN ({})".format(quoted))

        # Filtra a demanda por LINHA (chave de ligação demanda→GTFS)
        demanda = QgsProject.instance().mapLayersByName('dados_demanda')
        if demanda:
            demanda[0].setSubsetString(
                "LINHA = '{}'".format(route_name.replace("'", "''")))

        # Carrega os horários por parada da linha (segundo plano)
        self._horarios_task = _HorariosTask(gpkg, route_name)
        QgsApplication.taskManager().addTask(self._horarios_task)

    def map_changed(self):
        layer = self.mMapLayerComboBox.currentLayer()
        self.mFieldComboBox.setLayer(layer)
        self.mFieldComboBox.currentField()
        field = self.mFieldComboBox.currentField()
        picker = self.mFeaturePickerWidget
        picker.setLayer(layer)
        picker.setDisplayExpression(field)
        feature = picker.feature()
        #value = self.mFeatureListComboBox.setCurrentFeature()
        #print(value)


    def gtfsClicked(self):
        """Verifica o GTFS e garante a presença de calendar.txt.

        Pela especificação GTFS, um feed deve conter calendar.txt OU
        calendar_dates.txt. Como o leitor embutido (gtfs_reader.py) espera
        calendar.txt, quando o feed só traz calendar_dates.txt geramos um
        calendar.txt válido a partir dele e reempacotamos em
        'gtfs_corrigido.zip'.
        """
        gtfs_path = self.gtfs_widget.filePath()
        if not gtfs_path or not os.path.isfile(gtfs_path):
            iface.messageBar().pushMessage(
                "Erro", "Selecione um arquivo GTFS (.zip) válido.",
                level=Qgis.Critical, duration=10)
            return

        with ZipFile(gtfs_path) as zin:
            names = zin.namelist()
            has_calendar = 'calendar.txt' in names
            has_calendar_dates = 'calendar_dates.txt' in names

            if has_calendar:
                iface.messageBar().pushMessage(
                    "Info",
                    "O GTFS já contém calendar.txt; nenhuma correção necessária.",
                    level=Qgis.Info, duration=10)
                return

            if not has_calendar_dates:
                iface.messageBar().pushMessage(
                    "Erro",
                    "O GTFS não contém calendar.txt nem calendar_dates.txt — "
                    "feed inválido segundo a especificação.",
                    level=Qgis.Critical, duration=10)
                return

            # Feed só com calendar_dates.txt: sintetiza calendar.txt a partir dele.
            with zin.open('calendar_dates.txt') as raw:
                stream = io.TextIOWrapper(raw, encoding='utf-8-sig', newline='')
                calendar_txt = self._calendar_from_dates(stream)

            out_path = os.path.join(os.path.dirname(gtfs_path), 'gtfs_corrigido.zip')
            with ZipFile(out_path, 'w', zipfile.ZIP_DEFLATED) as zout:
                for name in names:
                    if name == 'calendar_dates.txt':
                        continue  # substituído pelo calendar.txt sintetizado
                    zout.writestr(name, zin.read(name))
                zout.writestr('calendar.txt', calendar_txt)

        iface.messageBar().pushMessage(
            "Info",
            "calendar.txt gerado a partir de calendar_dates.txt. "
            "Utilize o arquivo 'gtfs_corrigido.zip'.",
            level=Qgis.Info, duration=10)

    @staticmethod
    def _calendar_from_dates(text_stream):
        """Gera o conteúdo de calendar.txt a partir de calendar_dates.txt.

        calendar_dates.txt lista, por service_id, datas com exception_type=1
        (serviço adicionado) ou =2 (serviço removido). Para cada service_id,
        deduzimos quais dias da semana operam — a partir das datas com
        exception_type=1 — e o intervalo [start_date, end_date], produzindo o
        serviço semanal regular exigido por calendar.txt.

        Observação: é uma aproximação. O padrão semanal é reconstruído das
        datas explicitamente atendidas; feeds com operação irregular podem
        não ser representados fielmente por um calendar.txt semanal.
        """
        weekdays = ['monday', 'tuesday', 'wednesday', 'thursday',
                    'friday', 'saturday', 'sunday']
        services = {}  # service_id -> {'days': set(0..6), 'min': str, 'max': str}

        reader = csv.DictReader(text_stream)
        for row in reader:
            # Tolera espaços e BOM nos cabeçalhos/valores
            row = {(k or '').strip(): (v or '').strip() for k, v in row.items()}
            if row.get('exception_type') != '1':
                continue  # só datas adicionadas definem operação regular
            sid = row.get('service_id')
            date = row.get('date')
            if not sid or not date:
                continue
            weekday = datetime.strptime(date, '%Y%m%d').weekday()  # 0=seg .. 6=dom
            svc = services.setdefault(
                sid, {'days': set(), 'min': date, 'max': date})
            svc['days'].add(weekday)
            svc['min'] = min(svc['min'], date)
            svc['max'] = max(svc['max'], date)

        header = 'service_id,' + ','.join(weekdays) + ',start_date,end_date'
        lines = [header]
        for sid, svc in services.items():
            flags = ['1' if i in svc['days'] else '0' for i in range(7)]
            lines.append(','.join([sid] + flags + [svc['min'], svc['max']]))
        return '\n'.join(lines) + '\n'

    def dataClicked(self):
        """Carrega o CSV de demanda num GeoPackage (sigt.gpkg) em segundo
        plano. A ligação com o GTFS é feita por LINHA (route_short_name),
        sem campo derivado."""
        data_path = self.data_widget.filePath()
        if not data_path or not os.path.isfile(data_path):
            iface.messageBar().pushMessage(
                "Erro", "Selecione um arquivo CSV de demanda válido.",
                level=Qgis.Critical, duration=10)
            return

        gpkg_path = os.path.join(os.path.dirname(data_path), 'sigt.gpkg')
        self._demand_task = _DemandLoadTask(data_path, gpkg_path)
        QgsApplication.taskManager().addTask(self._demand_task)
        iface.messageBar().pushMessage(
            "Info",
            "Carregando dados de demanda em segundo plano… acompanhe o "
            "Gerenciador de Tarefas do QGIS.",
            level=Qgis.Info, duration=8)



    def _resolve_gpkg(self, prompt_if_missing=False):
        """Localiza o GeoPackage do GTFS por quatro estratégias em cascata.

        1. self._gpkg_path — memória da sessão atual.
        2. Propriedade 'gpkg_path' do QgsProject — persiste no .qgs/.qgz.
        3. Inferência a partir das camadas GTFS já no projeto: extrai o
           caminho do source() da primeira camada encontrada, resolvendo
           caminhos relativos contra o diretório do projeto.
        4. Diálogo de arquivo (só quando prompt_if_missing=True).

        Retorna o caminho absoluto do .gpkg, ou None se não encontrado."""
        # 1. Instância
        gpkg = getattr(self, '_gpkg_path', None)
        if gpkg and os.path.isfile(gpkg):
            return gpkg

        # 2. Propriedade do projeto
        gpkg = QgsProject.instance().readEntry('SIG-Bus', 'gpkg_path', '')[0]
        if gpkg and os.path.isfile(gpkg):
            self._gpkg_path = gpkg
            return gpkg

        # 3. Inferência — source() de camadas GTFS já carregadas
        project_home = QgsProject.instance().homePath()
        for name in ESSENTIAL_LAYERS:
            layers = QgsProject.instance().mapLayersByName(name)
            if not layers:
                continue
            # source() para OGR/GPKG: "/caminho/feed.gpkg|layername=stops"
            # Com caminhos relativos: "feed.gpkg|layername=stops"
            candidate = layers[0].source().split('|')[0].strip()
            if not os.path.isabs(candidate) and project_home:
                candidate = os.path.join(project_home, candidate)
            if candidate and os.path.isfile(candidate):
                self._gpkg_path = candidate
                QgsProject.instance().writeEntry(
                    'SIG-Bus', 'gpkg_path', candidate)
                return candidate

        if not prompt_if_missing:
            return None

        # 4. Diálogo de arquivo — usuário aponta o .gpkg manualmente
        from qgis.PyQt.QtWidgets import QFileDialog
        start_dir = project_home or os.path.expanduser('~')
        gpkg, _ = QFileDialog.getOpenFileName(
            self, 'Selecione o GeoPackage do GTFS', start_dir,
            'GeoPackage (*.gpkg)')
        if not gpkg:
            return None
        self._gpkg_path = gpkg
        QgsProject.instance().writeEntry('SIG-Bus', 'gpkg_path', gpkg)
        return gpkg

    def _resolve_demand_gpkg(self, gtfs_gpkg):
        """Localiza o GeoPackage que contém dados_demanda.

        Tenta em ordem:
        1. Camada 'dados_demanda' já no projeto → extrai o caminho do source().
        2. sigt.gpkg ao lado do CSV selecionado no data_widget.
        3. O próprio GTFS GeoPackage (caso demanda e GTFS compartilhem o arquivo)."""
        project_home = QgsProject.instance().homePath()

        # 1. Projeto — source() da camada dados_demanda
        for lyr in QgsProject.instance().mapLayersByName('dados_demanda'):
            src = lyr.source().split('|')[0].strip()
            if not os.path.isabs(src) and project_home:
                src = os.path.join(project_home, src)
            if os.path.isfile(src):
                return src

        # 2. Ao lado do CSV
        csv_path = self.data_widget.filePath()
        if csv_path:
            candidate = os.path.join(os.path.dirname(csv_path), 'sigt.gpkg')
            if os.path.isfile(candidate):
                return candidate

        # 3. Mesmo arquivo do GTFS
        if gtfs_gpkg and os.path.isfile(gtfs_gpkg):
            try:
                with sqlite3.connect(gtfs_gpkg) as c:
                    tbls = {r[0] for r in c.execute(
                        "SELECT name FROM sqlite_master WHERE type='table'")}
                if 'dados_demanda' in tbls:
                    return gtfs_gpkg
            except sqlite3.Error:
                pass

        return None

    def reconnectGpkg(self):
        """Reconecta o GeoPackage do GTFS e readiciona as camadas ao projeto.

        Útil quando o QGIS foi fechado e reaberto. Usa _resolve_gpkg() para
        encontrar o arquivo; se nenhuma estratégia automática funcionar, abre
        um diálogo para o usuário apontar o .gpkg manualmente."""
        gpkg = self._resolve_gpkg(prompt_if_missing=True)
        if not gpkg:
            return  # usuário cancelou o diálogo

        project = QgsProject.instance()
        added = []

        # Adiciona camadas essenciais ausentes do projeto (sem duplicar)
        for name in ESSENTIAL_LAYERS:
            if project.mapLayersByName(name):
                continue
            layer = QgsVectorLayer(gpkg + '|layername=' + name, name, 'ogr')
            if layer.isValid():
                project.addMapLayer(layer)
                added.append(name)

        msg = "GeoPackage reconectado ({}).".format(os.path.basename(gpkg))
        if added:
            msg += " Camadas readicionadas: {}.".format(', '.join(added))
        msg += " Use 'Filtrar dados' para carregar os horários da linha."
        iface.messageBar().pushMessage("Info", msg, level=Qgis.Info, duration=12)

    def alocacaoClicked(self):
        """Aloca os embarques do CSV de demanda nos tramos da linha selecionada.

        Requer: linha filtrada (mFeaturePickerWidget), CSV de demanda
        selecionado em 'data_widget' e GeoPackage do GTFS acessível."""
        field = self.mFieldComboBox.currentField()
        feature = self.mFeaturePickerWidget.feature()
        if not feature.isValid() or not field:
            iface.messageBar().pushMessage(
                "Aviso", "Escolha uma linha antes de alocar a demanda.",
                level=Qgis.Warning, duration=8)
            return
        value = feature[field]
        if value is None:
            return

        gpkg = self._resolve_gpkg()
        if not gpkg:
            iface.messageBar().pushMessage(
                "Aviso",
                "GeoPackage não encontrado. Use 'Reconectar GeoPackage' "
                "para localizá-lo.",
                level=Qgis.Warning, duration=8)
            return

        # Localiza onde dados_demanda foi gravado (pode ser sigt.gpkg separado)
        demand_gpkg = self._resolve_demand_gpkg(gpkg)
        if not demand_gpkg:
            iface.messageBar().pushMessage(
                "Aviso",
                "Dados de demanda não encontrados. Use 'Inserir' para "
                "carregá-los antes de alocar.",
                level=Qgis.Warning, duration=8)
            return

        hora_text = self.combo_hora.currentText()
        hora = None if hora_text == 'Total geral' else int(hora_text.replace('h', ''))

        self._alocacao_task = _AlocacaoTask(
            gpkg, str(value), hora=hora, demand_gpkg=demand_gpkg)
        QgsApplication.taskManager().addTask(self._alocacao_task)
        iface.messageBar().pushMessage(
            "Info",
            "Alocando demanda para a linha {} ({}) em segundo plano…".format(
                value, hora_text),
            level=Qgis.Info, duration=6)

    def diagramaClicked(self):
        """Abre o Diagrama de Blocos (tempo × linha/sentido) para o GTFS atual.

        Reaproveita _resolve_gpkg() para localizar o GeoPackage. O import é
        tardio: um problema nos módulos do diagrama não impede o restante do
        plugin de carregar."""
        gpkg = self._resolve_gpkg(prompt_if_missing=True)
        if not gpkg:
            iface.messageBar().pushMessage(
                'Aviso',
                "GeoPackage do GTFS não encontrado. Carregue um GTFS ou use "
                "'Reconectar GeoPackage'.",
                level=Qgis.Warning, duration=8)
            return
        try:
            from .block_diagram_dialog import BlockDiagramDialog
        except Exception as e:   # noqa: BLE001
            iface.messageBar().pushMessage(
                'Erro', 'Falha ao abrir o Diagrama de Blocos: {}'.format(e),
                level=Qgis.Critical, duration=10)
            return
        # Parenteia à janela principal do QGIS (não a este diálogo), para a
        # janela do diagrama sobreviver ao fechamento do SIG-Bus. A referência
        # é mantida aqui (este diálogo persiste via plugin) para não ser
        # coletado pelo GC.
        self._block_dialog = BlockDiagramDialog(gpkg, parent=iface.mainWindow())
        self._block_dialog.show()
        self._block_dialog.raise_()
        # Fecha a janela do SIG-Bus ao abrir o diagrama.
        self.close()

    def loadGtfs(self):
        """Carrega o GTFS selecionado num GeoPackage e adiciona as camadas
        ao projeto, usando o leitor embutido (gtfs_reader.py).

        Substitui a antiga integração com o plugin externo GTFS Loader:
        não instala nem invoca outro plugin. Se houver 'gtfs_corrigido.zip'
        (gerado por 'Verificar GTFS'), ele é preferido."""
        gtfs_path = self.gtfs_widget.filePath()
        if not gtfs_path or not os.path.isfile(gtfs_path):
            iface.messageBar().pushMessage(
                "Erro", "Selecione um arquivo GTFS (.zip) válido.",
                level=Qgis.Critical, duration=10)
            return

        # Prefere o feed corrigido, se existir ao lado do original.
        corrigido = os.path.join(os.path.dirname(gtfs_path), 'gtfs_corrigido.zip')
        if os.path.isfile(corrigido):
            gtfs_path = corrigido

        gpkg_path = os.path.splitext(gtfs_path)[0] + '.gpkg'
        # Guardado para o filtro reconstruir a camada virtual por linha.
        # Também persiste nas propriedades do projeto para sobreviver ao
        # fechamento/reabertura do QGIS (reconnectGpkg lê daqui).
        self._gpkg_path = gpkg_path
        QgsProject.instance().writeEntry('SIG-Bus', 'gpkg_path', gpkg_path)

        # O GTFS pode ser grande (stop_times.txt costuma ter dezenas/centenas
        # de MB), então a gravação roda numa tarefa de fundo para não congelar
        # a interface do QGIS. As camadas são adicionadas ao projeto no
        # callback finished(), que executa na thread principal.
        self._load_task = _GtfsLoadTask(gtfs_path, gpkg_path)
        QgsApplication.taskManager().addTask(self._load_task)
        iface.messageBar().pushMessage(
            "Info",
            "Carregando GTFS em segundo plano… acompanhe o Gerenciador de "
            "Tarefas do QGIS.",
            level=Qgis.Info, duration=8)

    # ------------------------------------------------------------------
    def relatorioClicked(self):
        """Gera layout de impressão A4 landscape e exporta para PDF.

        Requer: camada 'tramos_demanda' gerada por 'Alocar Demanda'.
        Produz: mapa da linha filtrada, legenda, título e dois gráficos
        de barras (ida e volta) com embarques agrupados por cluster K-means
        espacial."""
        project = QgsProject.instance()

        # 1. Verificar pré-condições ----------------------------------------
        tramos_layers = project.mapLayersByName('tramos_demanda')
        if not tramos_layers:
            iface.messageBar().pushMessage(
                'Aviso',
                "Execute 'Alocar Demanda' antes de gerar o relatório.",
                level=Qgis.Warning, duration=8)
            return
        tramos = tramos_layers[0]
        feats = list(tramos.getFeatures())
        if not feats:
            iface.messageBar().pushMessage(
                'Aviso', "Camada 'tramos_demanda' está vazia.",
                level=Qgis.Warning, duration=8)
            return

        linha    = feats[0]['linha']
        hora_str = feats[0]['hora']
        titulo   = 'Linha {} — Alocação de Demanda — {}'.format(linha, hora_str)

        # 2. Extrair pontos de embarque por sentido -------------------------
        def _stops(sentido_val):
            result = []
            for f in feats:
                if f['sentido'] != sentido_val:
                    continue
                geom = f.geometry()
                if geom.isEmpty():
                    continue
                poly = geom.asPolyline()
                if not poly:
                    continue
                # (QgsPointXY, embarques, seq_from) — início do segmento = parada A
                result.append((poly[0], int(f['embarques'] or 0), int(f['seq_from'] or 0)))
            return result

        stops_ida   = _stops('ida')
        stops_volta = _stops('volta')

        # 3. k automático: sqrt(n) clampado entre 3 e 10 -------------------
        def auto_k(n):
            return max(3, min(10, round(n ** 0.5)))

        # 4. Clustering K-means --------------------------------------------
        series_ida,   assign_ida   = self._cluster_stops(stops_ida,   auto_k(len(stops_ida)))   if stops_ida   else ([], {})
        series_volta, assign_volta = self._cluster_stops(stops_volta, auto_k(len(stops_volta))) if stops_volta else ([], {})

        # 5. Preenche cluster_id em tramos_demanda (sem mexer na simbologia;
        #    os renderers dos dois mapas são montados na etapa 8).
        if assign_ida or assign_volta:
            self._assign_cluster_ids(tramos, assign_ida, assign_volta)

        # 6. Gráficos → PNGs temporários -----------------------------------
        #    Mesma cor por cluster que o mapa de clusters do relatório.
        cluster_colors = self._cluster_color_map(assign_ida, assign_volta)
        png_ida   = self._make_chart(series_ida,   'ida',   hora_str, cluster_colors)
        png_volta = self._make_chart(series_volta, 'volta', hora_str, cluster_colors)
        tmp_pngs  = [p for p in [png_ida, png_volta] if p]
        if not tmp_pngs:
            iface.messageBar().pushMessage(
                'Aviso',
                'Gráficos não gerados — verifique o log SIG-Bus para detalhes.',
                level=Qgis.Warning, duration=8)

        # 7. Caminho de saída ----------------------------------------------
        gpkg = self._resolve_gpkg() or ''
        default = os.path.join(
            os.path.dirname(gpkg),
            'relatorio_{}_{}.pdf'.format(linha, hora_str.replace(' ', '_')))
        save_path, _ = QFileDialog.getSaveFileName(
            self, 'Salvar relatório', default, 'PDF (*.pdf)')
        if not save_path:
            for p in tmp_pngs:
                try:
                    os.unlink(p)
                except OSError:
                    pass
            return

        # 8. Layout — uma página A4 landscape por sentido com dados ----------
        MM = QgsUnitTypes.LayoutMillimeters
        PAGE_W, PAGE_H, PAGE_GAP = 297.0, 210.0, 10.0  # mm

        # Páginas a criar: apenas sentidos com dados de demanda
        pages_data = []
        if series_ida:
            pages_data.append(('Ida',   png_ida))
        if series_volta:
            pages_data.append(('Volta', png_volta))

        if not pages_data:
            iface.messageBar().pushMessage(
                'Aviso', 'Sem dados de demanda para gerar o relatório.',
                level=Qgis.Warning, duration=8)
            for p in tmp_pngs:
                try:
                    os.unlink(p)
                except OSError:
                    pass
            return

        # Extensão do mapa — compartilhada por todas as páginas
        ext = tramos.extent()
        ext.grow(max(ext.width(), ext.height()) * 0.10)
        proj_crs = project.crs()
        if tramos.crs() != proj_crs:
            xform = QgsCoordinateTransform(tramos.crs(), proj_crs, project)
            ext = xform.transformBoundingBox(ext)

        title_font = QFont('Sans Serif', 12)
        title_font.setBold(True)
        cap_font = QFont('Sans Serif', 8)
        cap_font.setBold(True)

        # Camadas de fundo visíveis (exclui tramos — filtrados por sentido — e
        # 'shapes', já que os tramos cobrem o traçado da linha)
        proj_tree = project.layerTreeRoot()
        base_layers = []
        for lyr in project.mapLayers().values():
            if not getattr(lyr, 'isSpatial', lambda: False)():
                continue
            if lyr.name() in ('tramos_demanda', 'shapes'):
                continue
            node = proj_tree.findLayer(lyr.id())
            if node and node.isVisible():
                base_layers.append(lyr)

        # Legenda construída a partir de camadas explícitas (topo) + fundo.
        def _legend_tree(top_layers):
            root = QgsLayerTree()
            for lyr in list(top_layers) + base_layers:
                root.addLayer(lyr)
            return root

        # Classes de carga compartilhadas pelas duas páginas (comparáveis).
        load_values = [int(f['passageiros_acum'] or 0)
                       for f in tramos.getFeatures()]

        layout = QgsPrintLayout(project)
        layout.initializeDefaults()
        layout.setName(titulo)
        layout.pageCollection().page(0).setPageSize(
            QgsLayoutSize(PAGE_W, PAGE_H, MM))

        # Refs p/ evitar GC; ids das camadas temporárias p/ limpar após exportar
        _legend_trees  = []
        _tmp_layers    = []
        _tmp_layer_ids = []

        def _make_tmp(sentido_val, renderer, suffix):
            """Camada de memória com os tramos do sentido, com renderer próprio.
            Registrada no projeto (sem ir p/ a árvore) para a legenda resolvê-la."""
            lyr = QgsVectorLayer(
                'LineString?crs={}'.format(tramos.crs().authid()),
                '_tmp_{}_{}'.format(suffix, sentido_val), 'memory')
            prov = lyr.dataProvider()
            prov.addAttributes(list(tramos.fields()))
            lyr.updateFields()
            prov.addFeatures([f for f in tramos.getFeatures()
                              if f['sentido'] == sentido_val])
            lyr.updateExtents()
            lyr.setRenderer(renderer)
            project.addMapLayer(lyr, False)
            _tmp_layers.append(lyr)
            _tmp_layer_ids.append(lyr.id())
            return lyr

        for page_idx, (sentido_label, png_path) in enumerate(pages_data):
            if page_idx > 0:
                extra_page = QgsLayoutItemPage(layout)
                extra_page.setPageSize(QgsLayoutSize(PAGE_W, PAGE_H, MM))
                layout.pageCollection().addPage(extra_page)

            y0          = page_idx * (PAGE_H + PAGE_GAP)
            sentido_val = sentido_label.lower()
            dir_titulo  = '{} — Sentido {}'.format(titulo, sentido_label)

            # Título
            lbl = QgsLayoutItemLabel(layout)
            lbl.setText(dir_titulo)
            lbl.setFont(title_font)
            layout.addLayoutItem(lbl)
            lbl.attemptMove(QgsLayoutPoint(10, y0 + 4, MM))
            lbl.attemptResize(QgsLayoutSize(277, 10, MM))

            # Camadas temporárias do sentido: uma por mapa (carga × cluster)
            ftmp_load = _make_tmp(
                sentido_val, make_load_renderer(load_values), 'carga')
            ftmp_clu  = _make_tmp(
                sentido_val, make_cluster_renderer(cluster_colors), 'cluster')

            # --- Mapa A: Carregamento (espessura por passageiros_acum) -------
            mapA = QgsLayoutItemMap(layout)
            layout.addLayoutItem(mapA)
            mapA.attemptMove(QgsLayoutPoint(10, y0 + 16, MM))
            mapA.attemptResize(QgsLayoutSize(135, 116, MM))
            mapA.setCrs(proj_crs)
            mapA.setExtent(ext)
            mapA.setFollowVisibilityPreset(False)
            mapA.setLayers([ftmp_load] + base_layers)
            mapA.setFrameEnabled(True)

            sbarA = QgsLayoutItemScaleBar(layout)
            layout.addLayoutItem(sbarA)
            sbarA.setLinkedMap(mapA)
            sbarA.attemptMove(QgsLayoutPoint(13, y0 + 123, MM))
            sbarA.attemptResize(QgsLayoutSize(45, 6, MM))

            capA = QgsLayoutItemLabel(layout)
            capA.setText('Carregamento — espessura ∝ passageiros acumulados')
            capA.setFont(cap_font)
            layout.addLayoutItem(capA)
            capA.attemptMove(QgsLayoutPoint(10, y0 + 133, MM))
            capA.attemptResize(QgsLayoutSize(135, 6, MM))

            # --- Mapa B: Clusters (cor por cluster_id) -----------------------
            mapB = QgsLayoutItemMap(layout)
            layout.addLayoutItem(mapB)
            mapB.attemptMove(QgsLayoutPoint(152, y0 + 16, MM))
            mapB.attemptResize(QgsLayoutSize(135, 116, MM))
            mapB.setCrs(proj_crs)
            mapB.setExtent(ext)
            mapB.setFollowVisibilityPreset(False)
            mapB.setLayers([ftmp_clu] + base_layers)
            mapB.setFrameEnabled(True)

            sbarB = QgsLayoutItemScaleBar(layout)
            layout.addLayoutItem(sbarB)
            sbarB.setLinkedMap(mapB)
            sbarB.attemptMove(QgsLayoutPoint(155, y0 + 123, MM))
            sbarB.attemptResize(QgsLayoutSize(45, 6, MM))

            capB = QgsLayoutItemLabel(layout)
            capB.setText('Clusters de embarque — cores iguais às do gráfico')
            capB.setFont(cap_font)
            layout.addLayoutItem(capB)
            capB.attemptMove(QgsLayoutPoint(152, y0 + 133, MM))
            capB.attemptResize(QgsLayoutSize(135, 6, MM))

            # --- Legenda do Mapa A (classes de carga) ------------------------
            ltree = _legend_tree([ftmp_load])
            _legend_trees.append(ltree)
            legend = QgsLayoutItemLegend(layout)
            legend.setAutoUpdateModel(False)
            legend.model().setRootGroup(ltree)
            legend.setTitle('Carga (pax/tramo)')
            layout.addLayoutItem(legend)
            legend.attemptMove(QgsLayoutPoint(10, y0 + 141, MM))
            legend.attemptResize(QgsLayoutSize(120, 62, MM))
            legend.setFrameEnabled(True)

            # --- Gráfico do Mapa B (barras por cluster; dobra de legenda) ----
            # Frame 74 × 60 mm → proporção 1.233 = proporção da imagem (825×669)
            if png_path:
                pic = QgsLayoutItemPicture(layout)
                pic.setPicturePath(png_path)
                layout.addLayoutItem(pic)
                pic.attemptMove(QgsLayoutPoint(152, y0 + 141, MM))
                pic.attemptResize(QgsLayoutSize(74, 60, MM))
                pic.setFrameEnabled(True)

        # Substituir layout anterior de mesmo nome, se existir
        mgr = project.layoutManager()
        old_layout = mgr.layoutByName(titulo)
        if old_layout:
            mgr.removeLayout(old_layout)
        mgr.addLayout(layout)

        # 9. Exportar PDF --------------------------------------------------
        exporter = QgsLayoutExporter(layout)
        res = exporter.exportToPdf(
            save_path, QgsLayoutExporter.PdfExportSettings())

        # Remove as camadas temporárias do projeto (usadas só para o export).
        if _tmp_layer_ids:
            project.removeMapLayers(_tmp_layer_ids)

        for p in tmp_pngs:
            try:
                os.unlink(p)
            except OSError:
                pass

        if res == QgsLayoutExporter.Success:
            iface.messageBar().pushMessage(
                'Info',
                'Relatório exportado: {}'.format(save_path),
                level=Qgis.Info, duration=12)
        else:
            iface.messageBar().pushMessage(
                'Erro',
                'Falha ao exportar PDF (código {}).'.format(res),
                level=Qgis.Critical, duration=10)

    def editEnterClicked(self):
        """
        Inicia ou retoma o modo de edição do GTFS.
        Clona o GeoPackage de origem para feed_edit.gpkg e prepara a cópia de trabalho.
        """
        gpkg = self._resolve_gpkg(prompt_if_missing=True)
        if not gpkg:
            iface.messageBar().pushMessage(
                "Aviso",
                "GTFS não encontrado — carregue ou reconecte o GeoPackage primeiro.",
                level=Qgis.Warning, duration=8
            )
            return

        wc = WorkingCopy(gpkg)

        if wc.is_active():
            reply = QMessageBox.question(
                self,
                "Edição em andamento",
                "Já existe uma edição em andamento. Recriar do zero? (Não = retomar a atual)",
                QMessageBox.Yes | QMessageBox.No,
                QMessageBox.No
            )
            if reply == QMessageBox.Yes:
                ok = wc.enter(overwrite=True)
            else:
                ok = True  # Retoma a edição existente
        else:
            ok = wc.enter()
            if not ok:
                iface.messageBar().pushMessage(
                    "Erro",
                    "Falha ao criar a cópia de trabalho do GeoPackage (feed_edit.gpkg).",
                    level=Qgis.Critical, duration=10
                )
                return

        if ok:
            self._working_copy = wc
            iface.messageBar().pushMessage(
                "Info",
                "Modo de edição do GTFS ativado com sucesso.",
                level=Qgis.Info, duration=8
            )
            self._refresh_edit_status()

    def editDiscardClicked(self):
        """
        Descarta a edição atual apagando o arquivo feed_edit.gpkg após confirmação do usuário.
        """
        if self._working_copy is None or not self._working_copy.is_active():
            iface.messageBar().pushMessage(
                "Aviso",
                "Nenhuma edição para descartar.",
                level=Qgis.Warning, duration=8
            )
            return

        reply = QMessageBox.question(
            self,
            "Descartar Edição",
            "Tem certeza que deseja descartar todas as alterações não salvas? Esta operação não pode ser desfeita.",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.No
        )

        if reply == QMessageBox.Yes:
            wc = self._working_copy
            if wc.discard():
                self._working_copy = None
                iface.messageBar().pushMessage(
                    "Info",
                    "Edição descartada e arquivo temporário excluído.",
                    level=Qgis.Info, duration=8
                )
                self._refresh_edit_status()
            else:
                iface.messageBar().pushMessage(
                    "Erro",
                    "Falha ao apagar o arquivo de edição temporário.",
                    level=Qgis.Critical, duration=10
                )

    def editOpenClicked(self):
        """
        Carrega a tabela de atributos nativa do QGIS a partir do feed_edit.gpkg,
        aplica restrição de leitura nos campos de ID travados e fecha o diálogo do SIG-Bus.
        """
        if self._working_copy is None or not self._working_copy.is_active():
            iface.messageBar().pushMessage(
                "Aviso",
                "Entre no modo edição primeiro.",
                level=Qgis.Warning, duration=8
            )
            return

        table = self.combo_edit_table.currentText()
        uri = self._working_copy.edit_path + '|layername=' + table
        layer = QgsVectorLayer(uri, 'edit_' + table, 'ogr')

        if not layer.isValid():
            iface.messageBar().pushMessage(
                "Erro",
                "Falha ao carregar a camada edit_{}.".format(table),
                level=Qgis.Critical, duration=10
            )
            return

        # Travar IDs do gtfs_schema
        if table in gtfs_schema.GTFS_FILES:
            cfg = layer.editFormConfig()
            columns = gtfs_schema.GTFS_FILES[table]["columns"]
            for col in columns:
                if not col.editable:
                    idx = layer.fields().indexFromName(col.name)
                    if idx >= 0:
                        cfg.setReadOnly(idx, True)
            layer.setEditFormConfig(cfg)

        QgsProject.instance().addMapLayer(layer)
        layer.startEditing()
        iface.showAttributeTable(layer)
        self._edit_layer = layer

        iface.messageBar().pushMessage(
            "Info",
            "Tabela edit_{} aberta para edição no QGIS. O diálogo foi fechado.".format(table),
            level=Qgis.Info, duration=8
        )
        self.close()

    def exportClicked(self):
        """
        Inicia a exportação dos dados do GeoPackage (ativo de edição ou original)
        para um arquivo .zip normalizado em segundo plano.
        """
        if self._working_copy is not None and self._working_copy.is_active():
            gpkg_source = self._working_copy.edit_path
        else:
            gpkg_source = self._resolve_gpkg(prompt_if_missing=True)

        if not gpkg_source:
            iface.messageBar().pushMessage(
                "Aviso",
                "GeoPackage não encontrado. Carregue ou reconecte o GTFS primeiro.",
                level=Qgis.Warning, duration=8
            )
            return

        save_path, _ = QFileDialog.getSaveFileName(
            self,
            "Exportar GTFS",
            "feed_novo.zip",
            "Zip (*.zip)"
        )
        if not save_path:
            return

        if not save_path.lower().endswith(".zip"):
            save_path += ".zip"

        task = GtfsExporter(gpkg_source, save_path)
        # ponytail: Mantemos a referência da task em self._export_task para
        # evitar que o Garbage Collector a destrua prematuramente.
        self._export_task = task
        QgsApplication.taskManager().addTask(task)

        iface.messageBar().pushMessage(
            "Info",
            "Exportando GTFS em segundo plano...",
            level=Qgis.Info, duration=8
        )

    def editStopsClicked(self):
        """
        Carrega a camada de paradas (stops) a partir de feed_edit.gpkg, trava o campo stop_id,
        inicia a edição, ativa a ferramenta de vértices e fecha o diálogo do SIG-Bus.
        """
        if self._working_copy is None or not self._working_copy.is_active():
            iface.messageBar().pushMessage(
                "Aviso",
                "Entre no modo edição primeiro.",
                level=Qgis.Warning, duration=8
            )
            return

        uri = self._working_copy.edit_path + '|layername=stops'
        layer = QgsVectorLayer(uri, 'edit_stops', 'ogr')

        if not layer.isValid():
            iface.messageBar().pushMessage(
                "Erro",
                "Falha ao carregar a camada edit_stops.",
                level=Qgis.Critical, duration=10
            )
            return

        # Travar stop_id para evitar alteracao indesejada
        cfg = layer.editFormConfig()
        idx = layer.fields().indexFromName('stop_id')
        if idx >= 0:
            cfg.setReadOnly(idx, True)
        layer.setEditFormConfig(cfg)

        QgsProject.instance().addMapLayer(layer)
        self._edit_stops_layer = layer
        iface.setActiveLayer(layer)
        layer.startEditing()

        # Ativa a ferramenta de vertices do QGIS se disponivel
        try:
            iface.actionVertexTool().trigger()
        except Exception:
            # ponytail: Nao impede o fluxo caso a versao do QGIS tenha outra acao/nome
            pass

        iface.messageBar().pushMessage(
            "Info",
            "Paradas em edição: mova os pontos e salve pela barra de edição do QGIS.",
            level=Qgis.Info, duration=8
        )
        self.close()

    def _refresh_edit_status(self):
        """
        Atualiza o rótulo de status e o estado de habilitação dos botões da aba de edição.
        """
        active = self._working_copy is not None and self._working_copy.is_active()
        if active:
            filename = os.path.basename(self._working_copy.edit_path)
            self.label_edit_status.setText("Edição em andamento: {}".format(filename))
            self.button_edit_enter.setEnabled(False)
            self.combo_edit_table.setEnabled(True)
            self.button_edit_open.setEnabled(True)
            self.button_edit_stops.setEnabled(True)
            self.button_edit_export.setEnabled(True)
            self.button_edit_discard.setEnabled(True)
        else:
            self.label_edit_status.setText("Nenhuma edição em andamento.")
            self.button_edit_enter.setEnabled(True)
            self.combo_edit_table.setEnabled(False)
            self.button_edit_open.setEnabled(False)
            self.button_edit_stops.setEnabled(False)
            self.button_edit_export.setEnabled(True)
            self.button_edit_discard.setEnabled(False)

    # ------------------------------------------------------------------
    def _cluster_stops(self, stop_list, k):
        """Aplica K-means espacial (native:kmeansclustering) nas paradas.

        stop_list: list of (QgsPointXY, embarques, seq_from)
        Retorna: (series, assignments)
          series:      list of (label, total_embarques) ordenado pelo seq_from
                       médio do cluster
          assignments: dict {seq_from -> label} para colorir os tramos no mapa"""
        empty = ([], {})
        if not stop_list:
            return empty
        k = min(k, len(stop_list))

        mem = QgsVectorLayer('Point?crs=EPSG:4326', '_km_tmp', 'memory')
        prov = mem.dataProvider()
        prov.addAttributes([
            QgsField('emb', QVariant.Int),
            QgsField('seq', QVariant.Int),
        ])
        mem.updateFields()
        fields = mem.fields()

        batch = []
        for pt, emb, seq in stop_list:
            f = QgsFeature(fields)
            f.setGeometry(QgsGeometry.fromPointXY(pt))
            f.setAttributes([emb, seq])
            batch.append(f)
        prov.addFeatures(batch)

        try:
            out = _processing.run('native:kmeansclustering', {
                'INPUT':    mem,
                'CLUSTERS': k,
                'OUTPUT':   'TEMPORARY_OUTPUT',
            })['OUTPUT']
        except Exception as exc:
            msg = 'K-means falhou: {}'.format(exc)
            QgsMessageLog.logMessage(msg, 'SIG-Bus', Qgis.Warning)
            iface.messageBar().pushMessage(
                'Aviso', 'Clustering falhou — gráficos omitidos. ' + msg,
                level=Qgis.Warning, duration=10)
            return empty

        # Agrega por cluster; ordena pelo seq médio para manter a
        # progressão geográfica da linha no eixo X do gráfico.
        agg = {}   # cluster_id -> [total_emb, sum_seq, count]
        raw_assignments = {}   # seq_from -> cluster_id (numérico)
        for f in out.getFeatures():
            cid = int(f['CLUSTER_ID'])
            seq = int(f['seq'] or 0)
            if cid not in agg:
                agg[cid] = [0, 0, 0]
            agg[cid][0] += int(f['emb'] or 0)
            agg[cid][1] += seq
            agg[cid][2] += 1
            raw_assignments[seq] = cid

        sorted_clusters = sorted(
            agg.items(),
            key=lambda x: x[1][1] / x[1][2] if x[1][2] else 0)

        # Mapeia cluster_id numérico → label legível (C1, C2, …)
        cid_to_label = {cid: 'C{}'.format(i + 1)
                        for i, (cid, _) in enumerate(sorted_clusters)}

        series      = [(cid_to_label[cid], data[0])
                       for cid, data in sorted_clusters]
        assignments = {seq: cid_to_label[cid]
                       for seq, cid in raw_assignments.items()}

        return series, assignments

    # ------------------------------------------------------------------
    def _assign_cluster_ids(self, tramos_layer, assign_ida, assign_volta):
        """Adiciona e preenche o campo 'cluster_id' em tramos_demanda a partir
        das atribuições do K-means (por seq_from e sentido). Não mexe na
        simbologia — o relatório monta os dois mapas (carga × cluster) com
        renderers próprios; o mapa vivo mantém a graduação de carga."""
        fields = tramos_layer.fields()
        if fields.indexFromName('cluster_id') < 0:
            tramos_layer.dataProvider().addAttributes(
                [QgsField('cluster_id', QVariant.String)])
            tramos_layer.updateFields()

        cidx = tramos_layer.fields().indexFromName('cluster_id')
        tramos_layer.startEditing()
        for feat in tramos_layer.getFeatures():
            seq     = int(feat['seq_from'] or 0)
            sentido = feat['sentido']
            cluster = (assign_ida if sentido == 'ida'
                       else assign_volta).get(seq, '?')
            tramos_layer.changeAttributeValue(feat.id(), cidx, cluster)
        tramos_layer.commitChanges()

    # ------------------------------------------------------------------
    def _make_chart(self, series, sentido, hora_str, cluster_colors=None):
        """Gera PNG de gráfico de barras com embarques por cluster.

        Desenhado com QPainter/QImage (PyQt5 sempre disponível no QGIS),
        sem dependência de matplotlib.

        series:         list of (label, embarques) ordenado por posição na linha
        sentido:        'ida' ou 'volta' (cor de fallback das barras)
        hora_str:       ex. '07h' ou 'Total'
        cluster_colors: dict {label_cluster: '#hex'} para colorir cada barra
                        com a mesma cor do mapa; None usa a cor do sentido.
        Retorna:        caminho do PNG temporário, ou None em caso de falha."""
        if not series:
            return None
        try:
            from qgis.PyQt.QtGui import (
                QImage, QPainter, QColor, QFont, QPen, QBrush,
            )
            from qgis.PyQt.QtCore import Qt, QRect

            labels    = [s[0] for s in series]
            values    = [s[1] for s in series]
            v_max     = max(values) if any(v > 0 for v in values) else 1
            dir_label = 'Ida' if sentido == 'ida' else 'Volta'
            fallback  = QColor('#2B7BB9' if sentido == 'ida' else '#C0392B')
            cluster_colors = cluster_colors or {}

            # Dimensões do canvas (px) — proporção 1.233 coincide com frame 111×90 mm
            W, H = 825, 669
            ML, MR, MT, MB = 80, 25, 55, 70  # margens esq/dir/topo/base

            img = QImage(W, H, QImage.Format_RGB32)
            img.fill(Qt.white)
            p = QPainter(img)
            p.setRenderHint(QPainter.Antialiasing)

            cw = W - ML - MR   # largura da área do gráfico
            ch = H - MT - MB   # altura da área do gráfico
            n  = len(labels)
            spacing = cw / n
            bw = int(spacing * 0.65)

            # Barras — cor por cluster (igual ao mapa); fallback = cor do sentido
            p.setPen(Qt.NoPen)
            for i, val in enumerate(values):
                bh = max(1, int(ch * val / v_max))
                x  = ML + int(i * spacing + (spacing - bw) / 2)
                hex_color = cluster_colors.get(labels[i])
                p.setBrush(QBrush(QColor(hex_color) if hex_color else fallback))
                p.drawRect(x, MT + ch - bh, bw, bh)

            # Rótulos numéricos acima das barras
            p.setPen(QColor('#333333'))
            p.setFont(QFont('Sans Serif', 7))
            for i, val in enumerate(values):
                bh = max(1, int(ch * val / v_max))
                xc = ML + int(i * spacing + spacing / 2)
                p.drawText(QRect(xc - 25, MT + ch - bh - 17, 50, 15),
                           Qt.AlignCenter, str(val))

            # Eixos
            axis_pen = QPen(QColor('#555555'))
            axis_pen.setWidth(1)
            p.setPen(axis_pen)
            p.drawLine(ML, MT, ML, MT + ch)
            p.drawLine(ML, MT + ch, ML + cw, MT + ch)

            # Linha de grade no topo (valor máximo)
            grid_pen = QPen(QColor('#cccccc'))
            grid_pen.setStyle(Qt.DotLine)
            p.setPen(grid_pen)
            p.drawLine(ML, MT, ML + cw, MT)
            mid_y = MT + ch // 2
            p.drawLine(ML, mid_y, ML + cw, mid_y)

            # Rótulos do eixo Y (0, metade, máximo)
            p.setPen(QColor('#555555'))
            p.setFont(QFont('Sans Serif', 7))
            for y_pos, y_val in [(MT + ch, 0), (mid_y, v_max // 2), (MT, v_max)]:
                p.drawText(QRect(0, y_pos - 8, ML - 6, 16),
                           Qt.AlignRight | Qt.AlignVCenter, str(y_val))

            # Rótulos do eixo X
            p.setFont(QFont('Sans Serif', 8))
            for i, label in enumerate(labels):
                xc = ML + int(i * spacing + spacing / 2)
                p.drawText(QRect(xc - 20, MT + ch + 5, 40, 18),
                           Qt.AlignCenter, label)

            # Título dos eixos
            p.drawText(QRect(ML, MT + ch + 30, cw, 18), Qt.AlignCenter, 'Cluster')
            p.save()
            p.translate(14, MT + ch // 2)
            p.rotate(-90)
            p.drawText(QRect(-50, -9, 100, 18), Qt.AlignCenter, 'Embarques')
            p.restore()

            # Título do gráfico
            title_font = QFont('Sans Serif', 9)
            title_font.setBold(True)
            p.setFont(title_font)
            p.setPen(QColor('#222222'))
            p.drawText(
                QRect(0, 6, W, 30), Qt.AlignCenter,
                'Embarques por cluster — {} ({})'.format(dir_label, hora_str))

            p.end()

            tmp = tempfile.NamedTemporaryFile(suffix='.png', delete=False)
            img.save(tmp.name, 'PNG')
            tmp.close()
            return tmp.name

        except Exception as exc:
            QgsMessageLog.logMessage(
                'Falha ao gerar gráfico: {}'.format(exc),
                'SIG-Bus', Qgis.Warning)
            return None