# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SigBusDialog
                                 A QGIS plugin
 Análise de transporte público (GTFS + dados de demanda)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-12
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Diego Camargo
        email                : diegocamargo.bft@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import csv
import io
import os
import sqlite3
import zipfile
from datetime import datetime
from zipfile import ZipFile

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtCore import QVariant
from qgis.core import (
    Qgis,
    QgsApplication,
    QgsCoordinateTransformContext,
    QgsFeature,
    QgsField,
    QgsGeometry,
    QgsMessageLog,
    QgsProject,
    QgsTask,
    QgsVectorFileWriter,
    QgsVectorLayer,
)
from qgis.utils import iface

from .gtfs_reader import (
    ESSENTIAL_LAYERS,
    GtfsError,
    GtfsReader,
    create_join_indexes,
)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'SigBus_dialog_base.ui'))


class _HorariosTask(QgsTask):
    """Monta a camada de pontos de horários por parada para uma LINHA.

    A linha é identificada por route_short_name (ex. '101'), porque o
    shape_id do GTFS da BHTrans é numérico e sem significado para o usuário.
    O join é: routes (route_short_name → route_id) ⋈ trips ⋈ stop_times.

    Estratégia:
    - stop_times × trips: lidos via sqlite3 (tabelas sem geometria — seguro).
    - Coordenadas das paradas: lidas da camada stops via OGR (tabela pequena).
    - Resultado: camada de pontos em memória — abre instantaneamente."""

    def __init__(self, gpkg_path, route_name):
        super().__init__('Carregando horários', QgsTask.CanCancel)
        self.gpkg_path = gpkg_path
        self.route_name = str(route_name)
        # (stop_id, seq, arr, dep, trip_id, route_id, shape_id, dir, svc, nome, wkt)
        self._rows = []
        self.error = None

    def run(self):
        try:
            # Coordenadas e nomes das paradas (tabela pequena, lida via OGR)
            stops_vlayer = QgsVectorLayer(
                self.gpkg_path + '|layername=stops', '_hp_stops', 'ogr')
            stop_data = {}  # stop_id -> (stop_name, wkt)
            for feat in stops_vlayer.getFeatures():
                stop_data[str(feat['stop_id'])] = (
                    str(feat['stop_name'] or ''),
                    feat.geometry().asWkt(),
                )

            with sqlite3.connect(self.gpkg_path) as conn:
                # Linha → route_id
                row = conn.execute(
                    "SELECT route_id FROM routes WHERE route_short_name=?",
                    (self.route_name,)).fetchone()
                if not row:
                    self.error = ("Linha '{}' não encontrada em routes "
                                  "(use route_short_name).".format(self.route_name))
                    return False
                route_id = row[0]

                rows = conn.execute(
                    "SELECT st.stop_id, st.stop_sequence, "
                    "st.arrival_time, st.departure_time, "
                    "t.trip_id, t.shape_id, t.direction_id, t.service_id "
                    "FROM stop_times AS st "
                    "JOIN trips AS t ON st.trip_id = t.trip_id "
                    "WHERE t.route_id = ?",
                    (route_id,)).fetchall()

            self.route_id = route_id
            for r in rows:
                stop_id = str(r[0])
                if stop_id not in stop_data:
                    continue
                stop_name, wkt = stop_data[stop_id]
                self._rows.append((
                    stop_id, r[1], r[2], r[3], r[4], r[5], r[6], r[7],
                    stop_name, wkt,
                ))
        except Exception as e:  # noqa: BLE001
            self.error = str(e)
            return False
        return True

    def finished(self, result):
        project = QgsProject.instance()
        for old in project.mapLayersByName('horarios_paradas'):
            project.removeMapLayer(old.id())

        if not result:
            iface.messageBar().pushMessage(
                "Erro",
                "Falha ao carregar horários: {}".format(
                    self.error or "tarefa interrompida."),
                level=Qgis.Critical, duration=10)
            return

        mem = QgsVectorLayer("Point?crs=EPSG:4326", "horarios_paradas", "memory")
        provider = mem.dataProvider()
        provider.addAttributes([
            QgsField('stop_id',        QVariant.String),
            QgsField('stop_sequence',  QVariant.String),
            QgsField('arrival_time',   QVariant.String),
            QgsField('departure_time', QVariant.String),
            QgsField('trip_id',        QVariant.String),
            QgsField('shape_id',       QVariant.String),
            QgsField('direction_id',   QVariant.String),
            QgsField('service_id',     QVariant.String),
            QgsField('stop_name',      QVariant.String),
            QgsField('linha',          QVariant.String),
        ])
        mem.updateFields()

        fields = mem.fields()
        idx = {f.name(): fields.indexFromName(f.name()) for f in fields}

        feats = []
        for (stop_id, seq, arr, dep, trip_id, shape_id, direction, svc,
             stop_name, wkt) in self._rows:
            feat = QgsFeature(fields)
            feat.setGeometry(QgsGeometry.fromWkt(wkt))
            attrs = feat.attributes()
            attrs[idx['stop_id']]        = stop_id
            attrs[idx['stop_sequence']]  = seq
            attrs[idx['arrival_time']]   = arr
            attrs[idx['departure_time']] = dep
            attrs[idx['trip_id']]        = trip_id
            attrs[idx['shape_id']]       = shape_id
            attrs[idx['direction_id']]   = direction
            attrs[idx['service_id']]     = svc
            attrs[idx['stop_name']]      = stop_name
            attrs[idx['linha']]          = self.route_name
            feat.setAttributes(attrs)
            feats.append(feat)

        provider.addFeatures(feats)
        mem.updateExtents()

        if mem.isValid() and mem.featureCount() > 0:
            project.addMapLayer(mem)
            iface.messageBar().pushMessage(
                "Info",
                "Horários carregados: {} registros para a linha {}.".format(
                    mem.featureCount(), self.route_name),
                level=Qgis.Info, duration=8)
        else:
            iface.messageBar().pushMessage(
                "Aviso",
                "Nenhum horário encontrado para a linha {}.".format(
                    self.route_name),
                level=Qgis.Warning, duration=8)


class _GtfsLoadTask(QgsTask):
    """Tarefa de fundo que carrega um GTFS num GeoPackage.

    O trabalho pesado de I/O (descompactar + gravar tabelas) roda em run(),
    fora da thread da GUI. A adição das camadas ao projeto acontece em
    finished(), que o QGIS executa na thread principal — único lugar seguro
    para mexer em QgsProject."""

    def __init__(self, gtfs_path, gpkg_path):
        super().__init__('Carregando GTFS', QgsTask.CanCancel)
        self.gtfs_path = gtfs_path
        self.gpkg_path = gpkg_path
        self.reader = GtfsReader(gtfs_path)
        self.layer_names = []
        self.has_shapes = False
        self.error = None

    def run(self):
        try:
            self.setProgress(5)
            # Importa as tabelas (parte mais demorada: stop_times).
            self.layer_names = self.reader.write(self.gpkg_path)
            self.setProgress(75)
            # Constrói as linhas a partir de shapes_point.
            shapes = self.reader.build_shapes_line(self.gpkg_path)
            self.has_shapes = shapes is not None and shapes.isValid()
            self.setProgress(90)
            # Índices nas chaves de join, para a camada virtual ser rápida.
            create_join_indexes(self.gpkg_path)
            self.setProgress(100)
        except GtfsError as e:
            self.error = str(e)
            return False
        except Exception as e:  # noqa: BLE001 — reporta qualquer falha à GUI
            self.error = str(e)
            return False
        finally:
            self.reader.cleanup()
        return True

    def finished(self, result):
        if not result:
            msg = self.error or "tarefa cancelada ou interrompida."
            iface.messageBar().pushMessage(
                "Erro", "Falha ao carregar o GTFS: {}".format(msg),
                level=Qgis.Critical, duration=10)
            return

        # Carrega apenas as camadas essenciais como camadas de mapa. As
        # demais tabelas (stop_times, fare_*, agency...) permanecem no
        # GeoPackage para alimentar os joins.
        for name in self.layer_names:
            if name not in ESSENTIAL_LAYERS:
                continue
            layer = QgsVectorLayer(
                self.gpkg_path + '|layername=' + name, name, 'ogr')
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)

        # Camada de linhas (shapes) construída a partir de shapes_point.
        if self.has_shapes:
            shapes_layer = QgsVectorLayer(
                self.gpkg_path + '|layername=shapes', 'shapes', 'ogr')
            if shapes_layer.isValid():
                QgsProject.instance().addMapLayer(shapes_layer)

        iface.messageBar().pushMessage(
            "Info",
            "GTFS carregado em '{}'. Escolha uma linha e clique em "
            "'Filtrar dados' para ver os horários por parada.".format(
                os.path.basename(self.gpkg_path)),
            level=Qgis.Info, duration=12)


class _DemandLoadTask(QgsTask):
    """Tarefa de fundo que carrega o CSV de demanda num GeoPackage e calcula
    o campo shape_id.

    O cálculo do shape_id é feito por um único UPDATE em SQL (o GeoPackage é
    SQLite), em vez do loop de edição feição-a-feição do código original —
    que rodava na thread da GUI e travava com muitos registros."""

    def __init__(self, data_path, gpkg_path):
        super().__init__('Carregando dados de demanda', QgsTask.CanCancel)
        self.data_path = data_path
        self.gpkg_path = gpkg_path
        self.error = None

    def run(self):
        try:
            self.setProgress(10)
            uri = (
                "file:///" + self.data_path +
                "?encoding={}&type=csv&delimiter={}&xField={}&yField={}"
                "&geomType=point&crs={}&spatialIndex=yes".format(
                    'windows-1252', ';', 'X', 'Y', 'EPSG:31983'))
            vlayer = QgsVectorLayer(uri, 'dados_demanda', 'delimitedtext')
            if not vlayer.isValid():
                self.error = ("CSV de demanda inválido (verifique as colunas "
                              "X/Y, o separador ';' e o encoding).")
                return False

            field_names = [f.name() for f in vlayer.fields()]
            for needed in ('LINHA', 'SUBLINHA', 'PC'):
                if needed not in field_names:
                    self.error = ("Coluna '{}' ausente no CSV de demanda."
                                  .format(needed))
                    return False

            # Não calculamos mais um shape_id sintético: o GTFS da BHTrans
            # usa shape_id numérico, sem relação com LINHA/SUBLINHA/PC. A
            # ligação demanda→GTFS é feita por LINHA = routes.route_short_name
            # (ver _AlocacaoTask / filterClicked). A coluna LINHA do CSV é a
            # chave; nada a derivar aqui.

            self.setProgress(50)
            opt = QgsVectorFileWriter.SaveVectorOptions()
            opt.driverName = 'GPKG'
            opt.layerName = 'dados_demanda'
            opt.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
            res = QgsVectorFileWriter.writeAsVectorFormatV3(
                vlayer, self.gpkg_path, QgsCoordinateTransformContext(), opt)
            if res[0] != QgsVectorFileWriter.NoError:
                self.error = "Falha ao gravar dados_demanda: {}".format(res[1])
                return False
            self.setProgress(100)
        except Exception as e:  # noqa: BLE001 — reporta qualquer falha à GUI
            self.error = str(e)
            return False
        return True

    def finished(self, result):
        if not result:
            iface.messageBar().pushMessage(
                "Erro",
                "Falha ao carregar a demanda: {}".format(
                    self.error or "tarefa interrompida."),
                level=Qgis.Critical, duration=10)
            return
        iface.addVectorLayer(
            self.gpkg_path + '|layername=dados_demanda',
            'dados_demanda', 'ogr')
        iface.messageBar().pushMessage(
            "Info", "Dados de demanda carregados (chave de ligação: LINHA).",
            level=Qgis.Info, duration=10)


class _AlocacaoTask(QgsTask):
    """Aloca embarques da demanda nos tramos de uma LINHA, por sentido.

    A linha é identificada por route_short_name (ex. '101'). Para cada
    sentido, usa o shape DOMINANTE (com mais viagens), pega a sequência de
    paradas desse shape e aloca os embarques (do CSV, filtrados por
    LINHA + PC) ao stop mais próximo. PC=1 → ida (direction_id 0),
    PC=2 → volta (direction_id 1).

    Saída: camada 'tramos_demanda' com segmentos por sentido e campo
    'embarques' pronto para simbologia graduada."""

    _PC_TO_DIR = {'1': '0', '2': '1'}       # PC (demanda) → direction_id (GTFS)
    _DIR_LABEL = {'0': 'ida', '1': 'volta'}

    def __init__(self, gpkg_path, route_name, hora=None, demand_gpkg=None):
        super().__init__('Alocando demanda', QgsTask.CanCancel)
        self.gpkg_path = gpkg_path          # GTFS (routes/trips/stops)
        self.demand_gpkg = demand_gpkg or gpkg_path   # dados_demanda
        self.route_name = str(route_name)
        # hora=None → Total geral; hora=int(0..23) → coluna horária
        self.hora = hora
        # (wkt, seq_a, sid_a, nome_a, sid_b, nome_b, emb, pc, sentido)
        self._segments = []
        self._avisos = []
        self.error = None

    def _find_emb_col(self, conn):
        """Devolve o nome real da coluna de embarques em dados_demanda."""
        cols = [row[1] for row in conn.execute("PRAGMA table_info(dados_demanda)")]
        if self.hora is None:
            for c in cols:
                if 'total' in c.lower() and 'geral' in c.lower():
                    return c
            return None
        hora_str = str(self.hora)
        return hora_str if hora_str in cols else None

    # ------------------------------------------------------------------
    def run(self):
        try:
            # 1. Coordenadas e nomes dos stops (OGR — tabela pequena) ----
            stops_vlayer = QgsVectorLayer(
                self.gpkg_path + '|layername=stops', '_aloc_s', 'ogr')
            stop_info = {}   # stop_id -> (nome, lat, lon)
            for feat in stops_vlayer.getFeatures():
                pt = feat.geometry().asPoint()
                stop_info[str(feat['stop_id'])] = (
                    str(feat['stop_name'] or ''), pt.y(), pt.x())

            # 2. Lê demanda de dados_demanda (arquivo separado ou mesmo gpkg)
            demanda_por_pc = {'1': [], '2': []}
            with sqlite3.connect(self.demand_gpkg) as dconn:
                tables = {r[0] for r in dconn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'")}
                if 'dados_demanda' not in tables:
                    self.error = ("Tabela 'dados_demanda' não encontrada em "
                                  "'{}'.".format(os.path.basename(self.demand_gpkg)))
                    return False

                emb_col = self._find_emb_col(dconn)
                if emb_col is None:
                    label = 'Total geral' if self.hora is None else str(self.hora)
                    self.error = ("Coluna '{}' não encontrada em dados_demanda."
                                  .format(label))
                    return False

                sql = ('SELECT "PC", "Latitude.WGS84", "Longitude.WGS84", "{}" '
                       'FROM dados_demanda WHERE "LINHA" = ?'.format(emb_col))
                for r in dconn.execute(sql, (self.route_name,)):
                    pc = str(r[0]).strip() if r[0] else ''
                    if pc not in demanda_por_pc:
                        continue
                    try:
                        lat = float(str(r[1]).strip())
                        lon = float(str(r[2]).strip())
                        emb = int(float(str(r[3] or 0)))
                    except (ValueError, TypeError):
                        continue
                    demanda_por_pc[pc].append((lat, lon, emb))

            if not any(demanda_por_pc.values()):
                self.error = ("Nenhuma demanda para a linha '{}' em dados_demanda."
                              .format(self.route_name))
                return False

            # 3. Queries GTFS (route_id, shape dominante, sequência de paradas)
            with sqlite3.connect(self.gpkg_path) as conn:
                row = conn.execute(
                    "SELECT route_id FROM routes WHERE route_short_name=?",
                    (self.route_name,)).fetchone()
                if not row:
                    self.error = ("Linha '{}' não encontrada em routes."
                                  .format(self.route_name))
                    return False
                route_id = row[0]

                # Processa cada sentido com demanda --------------------
                for pc, pts in demanda_por_pc.items():
                    if not pts:
                        continue
                    direction = self._PC_TO_DIR[pc]

                    # Shape dominante + contagem de viagens ----------
                    # Quando uma hora específica está selecionada, restringe
                    # às viagens que *iniciam* nessa hora (departure_time da
                    # primeira parada). Isso amarra a demanda horária às
                    # viagens que realmente serviram aquela janela de tempo.
                    if self.hora is not None:
                        shp = conn.execute(
                            "SELECT t.shape_id, COUNT(*) c "
                            "FROM trips t "
                            "JOIN stop_times st ON st.trip_id = t.trip_id "
                            "WHERE t.route_id = ? AND t.direction_id = ? "
                            "  AND CAST(st.stop_sequence AS INTEGER) = ("
                            "    SELECT MIN(CAST(ss.stop_sequence AS INTEGER))"
                            "    FROM stop_times ss WHERE ss.trip_id = t.trip_id"
                            "  )"
                            "  AND CAST(SUBSTR(st.departure_time,1,2) AS INTEGER) = ? "
                            "GROUP BY t.shape_id ORDER BY c DESC LIMIT 1",
                            (route_id, direction, self.hora)).fetchone()
                        if shp:
                            n_viagens = shp[1]
                        else:
                            # Sem viagens nessa hora: usa shape geral como fallback
                            shp = conn.execute(
                                "SELECT shape_id, COUNT(*) c FROM trips "
                                "WHERE route_id=? AND direction_id=? "
                                "GROUP BY shape_id ORDER BY c DESC LIMIT 1",
                                (route_id, direction)).fetchone()
                            n_viagens = 0
                            self._avisos.append(
                                "PC={}: nenhuma viagem iniciando às {:02d}h; "
                                "usando shape geral.".format(pc, self.hora))
                    else:
                        shp = conn.execute(
                            "SELECT shape_id, COUNT(*) c FROM trips "
                            "WHERE route_id=? AND direction_id=? "
                            "GROUP BY shape_id ORDER BY c DESC LIMIT 1",
                            (route_id, direction)).fetchone()
                        n_viagens = shp[1] if shp else 0

                    if not shp:
                        self._avisos.append(
                            "PC={} (sentido {}) sem viagens no GTFS."
                            .format(pc, self._DIR_LABEL.get(direction, direction)))
                        continue
                    shape_id = shp[0]

                    # Uma viagem desse shape → sequência de paradas
                    trip = conn.execute(
                        "SELECT trip_id FROM trips WHERE shape_id=? LIMIT 1",
                        (shape_id,)).fetchone()
                    stop_rows = conn.execute(
                        "SELECT stop_id, stop_sequence FROM stop_times "
                        "WHERE trip_id=? ORDER BY CAST(stop_sequence AS INTEGER)",
                        (trip[0],)).fetchall()

                    route_stops = []
                    for sid, seq in stop_rows:
                        info = stop_info.get(str(sid))
                        if not info:
                            continue
                        nome, lat, lon = info
                        try:
                            seq_i = int(seq)
                        except (TypeError, ValueError):
                            seq_i = 0
                        route_stops.append((seq_i, str(sid), nome, lat, lon))
                    route_stops.sort(key=lambda x: x[0])
                    if len(route_stops) < 2:
                        self._avisos.append(
                            "PC={}: menos de 2 paradas no shape {}."
                            .format(pc, shape_id))
                        continue

                    # Spatial join por menor distância lat/lon
                    stop_demand = {s[1]: 0 for s in route_stops}
                    for dlat, dlon, emb in pts:
                        nearest = min(
                            route_stops,
                            key=lambda s: (dlat - s[3])**2 + (dlon - s[4])**2)
                        stop_demand[nearest[1]] += emb

                    # Segmentos entre stops consecutivos, com passageiros acumulados.
                    # passageiros_acum[i] = soma dos embarques em todos os stops
                    # até o stop de partida do segmento i — representa a carga
                    # real do ônibus naquele tramo (assumindo sem descidas).
                    sentido = self._DIR_LABEL.get(direction, direction)
                    acum = 0
                    for i in range(len(route_stops) - 1):
                        seq_a, sid_a, nome_a, lat_a, lon_a = route_stops[i]
                        _sb, sid_b, nome_b, lat_b, lon_b = route_stops[i + 1]
                        emb_a = stop_demand[sid_a]
                        acum += emb_a
                        wkt = "LINESTRING({} {}, {} {})".format(
                            lon_a, lat_a, lon_b, lat_b)
                        self._segments.append((
                            wkt, seq_a, sid_a, nome_a, sid_b, nome_b,
                            emb_a, acum, pc, sentido, n_viagens))

            if not self._segments:
                self.error = ("Nenhum tramo gerado para a linha '{}'. {}"
                              .format(self.route_name, ' '.join(self._avisos)))
                return False

        except Exception as e:   # noqa: BLE001
            self.error = str(e)
            return False
        return True

    # ------------------------------------------------------------------
    def finished(self, result):
        project = QgsProject.instance()
        for old in project.mapLayersByName('tramos_demanda'):
            project.removeMapLayer(old.id())

        if not result:
            iface.messageBar().pushMessage(
                "Erro",
                "Falha na alocação: {}".format(self.error or "cancelada."),
                level=Qgis.Critical, duration=10)
            return

        mem = QgsVectorLayer("LineString?crs=EPSG:4326",
                             "tramos_demanda", "memory")
        prov = mem.dataProvider()
        prov.addAttributes([
            QgsField('seq_from',          QVariant.Int),
            QgsField('stop_id_from',      QVariant.String),
            QgsField('stop_name_from',    QVariant.String),
            QgsField('stop_id_to',        QVariant.String),
            QgsField('stop_name_to',      QVariant.String),
            QgsField('embarques',         QVariant.Int),
            QgsField('passageiros_acum',  QVariant.Int),
            QgsField('pc',                QVariant.String),
            QgsField('sentido',           QVariant.String),
            QgsField('linha',             QVariant.String),
            QgsField('hora',              QVariant.String),
            QgsField('n_viagens',         QVariant.Int),
        ])
        mem.updateFields()
        fields = mem.fields()
        idx = {f.name(): fields.indexFromName(f.name()) for f in fields}

        hora_label = 'Total' if self.hora is None else '{:02d}h'.format(self.hora)
        feats = []
        for (wkt, seq_a, sid_a, nome_a, sid_b, nome_b,
             emb, acum, pc, sentido, n_viagens) in self._segments:
            feat = QgsFeature(fields)
            feat.setGeometry(QgsGeometry.fromWkt(wkt))
            attrs = feat.attributes()
            attrs[idx['seq_from']]         = seq_a
            attrs[idx['stop_id_from']]     = sid_a
            attrs[idx['stop_name_from']]   = nome_a
            attrs[idx['stop_id_to']]       = sid_b
            attrs[idx['stop_name_to']]     = nome_b
            attrs[idx['embarques']]        = emb
            attrs[idx['passageiros_acum']] = acum
            attrs[idx['pc']]               = pc
            attrs[idx['sentido']]          = sentido
            attrs[idx['linha']]            = self.route_name
            attrs[idx['hora']]             = hora_label
            attrs[idx['n_viagens']]        = n_viagens
            feat.setAttributes(attrs)
            feats.append(feat)

        prov.addFeatures(feats)
        mem.updateExtents()

        if mem.isValid() and mem.featureCount() > 0:
            project.addMapLayer(mem)
            total_emb = sum(s[6] for s in self._segments)
            # Carga máxima = maior passageiros_acum entre todos os tramos
            carga_max = max(s[7] for s in self._segments)
            hora_label = 'Total' if self.hora is None else '{:02d}h'.format(self.hora)
            # Viagens por sentido (cada sentido pode ter valor diferente)
            viagens_por_pc = {}
            for s in self._segments:
                viagens_por_pc[s[8]] = s[10]  # pc -> n_viagens
            n_msg = ', '.join(
                '{} viagens sentido {}'.format(v, self._DIR_LABEL.get(self._PC_TO_DIR.get(p, p), p))
                for p, v in sorted(viagens_por_pc.items()) if v > 0)
            msg = ("{} tramos — {} embarques — carga máx. {} pax/tramo"
                   " — linha {} ({}).".format(
                       mem.featureCount(), total_emb, carga_max,
                       self.route_name, hora_label))
            if n_msg:
                msg += " GTFS: {}.".format(n_msg)
            if self._avisos:
                msg += " Avisos: " + ' '.join(self._avisos)
            iface.messageBar().pushMessage(
                "Info", msg, level=Qgis.Info, duration=12)
        else:
            iface.messageBar().pushMessage(
                "Aviso", "Nenhum tramo gerado.",
                level=Qgis.Warning, duration=8)


class SigBusDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SigBusDialog, self).__init__(parent)
        self.setupUi(self)
        self.gtfs_insert_button.clicked.connect(self.gtfsClicked)
        self.data_insert_button.clicked.connect(self.dataClicked)
        # O leitor de GTFS agora é embutido (gtfs_reader.py); não há mais
        # dependência do plugin externo GTFS Loader. O botão "Instalar GTFS
        # Loader" fica oculto e "Executar GTFS" carrega o feed diretamente.
        self.extrapackages.setVisible(False)
        self.button_gtfsgo.clicked.connect(self.loadGtfs)
        #Mudança de camada
        layer = self.mMapLayerComboBox.currentLayer()
        self.mMapLayerComboBox.layerChanged.connect(self.map_changed)
        self.mFieldComboBox.fieldChanged.connect(self.field_select)
        self.mFeaturePickerWidget.featureChanged.connect(self.field_select)
        #self.mFeatureListComboBox.setSourceLayer(self.mMapLayerComboBox.currentLayer())
        #Filter Button
        self.filterButton.clicked.connect(self.filterClicked)
        #self.mFeatureListComboBox.currentIndexChanged.connect(self.feature_select)
        #self.mFieldComboBox.indexChanged.connect(self.field_select)
        self.button_reconnect.clicked.connect(self.reconnectGpkg)
        self.button_alocar.clicked.connect(self.alocacaoClicked)

        # Seletor de hora: "Total geral" + horas 00h–23h
        self.combo_hora.addItem('Total geral')
        for h in range(24):
            self.combo_hora.addItem('{:02d}h'.format(h))

    def field_select(self):
        #field = self.mFieldComboBox.fields()
        layer = self.mMapLayerComboBox.currentLayer()
        field = self.mFieldComboBox.currentField()
        self.mFieldComboBox.setField(field)
        picker = self.mFeaturePickerWidget
        picker.setLayer(layer)
        picker.setDisplayExpression(field)
        feature = picker.feature()
        #print(feature[1])

        #Solução encontrada. Link para ajuda abaixo
        #https://qgis.org/pyqgis/master/core/QgsFeature.html#qgis.core.QgsFeature
        #https://gis.stackexchange.com/questions/409517/database-form-as-qgis-plugin-with-pyqgis-and-qtdesigner
        #Está saindo o número da posição do dado, precisa transformar no próprio dado. Ou não... Na verdade precisa
        #o próximo passo
        #self.mFeatureListComboBox.setDisplayExpression(field)
    #https://gis.stackexchange.com/questions/409517/database-form-as-qgis-plugin-with-pyqgis-and-qtdesigner

    def filterClicked(self):
        """Filtra pela LINHA escolhida (route_short_name).

        Espera-se que o usuário selecione a camada 'routes' e o campo
        'route_short_name' (ex.: '101'). A partir daí: destaca o traçado na
        camada 'shapes', filtra a demanda por LINHA e carrega os horários."""
        field = self.mFieldComboBox.currentField()
        feature = self.mFeaturePickerWidget.feature()
        if not feature.isValid() or not field:
            iface.messageBar().pushMessage(
                "Aviso", "Escolha uma linha antes de filtrar.",
                level=Qgis.Warning, duration=8)
            return
        value = feature[field]
        if value is None:
            return
        route_name = str(value).strip()

        gpkg = self._resolve_gpkg()
        if not gpkg:
            iface.messageBar().pushMessage(
                "Aviso",
                "GeoPackage não encontrado. Use 'Reconectar GeoPackage' "
                "para localizá-lo.",
                level=Qgis.Warning, duration=8)
            return

        # Resolve os shape_ids da linha (route_short_name → route_id → shapes)
        shape_ids = []
        try:
            with sqlite3.connect(gpkg) as conn:
                r = conn.execute(
                    "SELECT route_id FROM routes WHERE route_short_name=?",
                    (route_name,)).fetchone()
                if r:
                    shape_ids = [str(x[0]) for x in conn.execute(
                        "SELECT DISTINCT shape_id FROM trips WHERE route_id=?",
                        (r[0],)).fetchall() if x[0] is not None]
        except sqlite3.Error:
            pass

        # Destaca o traçado da linha na camada 'shapes'
        shapes_layers = QgsProject.instance().mapLayersByName('shapes')
        if shapes_layers and shape_ids:
            quoted = ", ".join(
                "'{}'".format(s.replace("'", "''")) for s in shape_ids)
            shapes_layers[0].setSubsetString(
                "shape_id IN ({})".format(quoted))

        # Filtra a demanda por LINHA (chave de ligação demanda→GTFS)
        demanda = QgsProject.instance().mapLayersByName('dados_demanda')
        if demanda:
            demanda[0].setSubsetString(
                "LINHA = '{}'".format(route_name.replace("'", "''")))

        # Carrega os horários por parada da linha (segundo plano)
        self._horarios_task = _HorariosTask(gpkg, route_name)
        QgsApplication.taskManager().addTask(self._horarios_task)

    def map_changed(self):
        layer = self.mMapLayerComboBox.currentLayer()
        self.mFieldComboBox.setLayer(layer)
        self.mFieldComboBox.currentField()
        field = self.mFieldComboBox.currentField()
        picker = self.mFeaturePickerWidget
        picker.setLayer(layer)
        picker.setDisplayExpression(field)
        feature = picker.feature()
        #value = self.mFeatureListComboBox.setCurrentFeature()
        #print(value)


    def gtfsClicked(self):
        """Verifica o GTFS e garante a presença de calendar.txt.

        Pela especificação GTFS, um feed deve conter calendar.txt OU
        calendar_dates.txt. Como o leitor embutido (gtfs_reader.py) espera
        calendar.txt, quando o feed só traz calendar_dates.txt geramos um
        calendar.txt válido a partir dele e reempacotamos em
        'gtfs_corrigido.zip'.
        """
        gtfs_path = self.gtfs_widget.filePath()
        if not gtfs_path or not os.path.isfile(gtfs_path):
            iface.messageBar().pushMessage(
                "Erro", "Selecione um arquivo GTFS (.zip) válido.",
                level=Qgis.Critical, duration=10)
            return

        with ZipFile(gtfs_path) as zin:
            names = zin.namelist()
            has_calendar = 'calendar.txt' in names
            has_calendar_dates = 'calendar_dates.txt' in names

            if has_calendar:
                iface.messageBar().pushMessage(
                    "Info",
                    "O GTFS já contém calendar.txt; nenhuma correção necessária.",
                    level=Qgis.Info, duration=10)
                return

            if not has_calendar_dates:
                iface.messageBar().pushMessage(
                    "Erro",
                    "O GTFS não contém calendar.txt nem calendar_dates.txt — "
                    "feed inválido segundo a especificação.",
                    level=Qgis.Critical, duration=10)
                return

            # Feed só com calendar_dates.txt: sintetiza calendar.txt a partir dele.
            with zin.open('calendar_dates.txt') as raw:
                stream = io.TextIOWrapper(raw, encoding='utf-8-sig', newline='')
                calendar_txt = self._calendar_from_dates(stream)

            out_path = os.path.join(os.path.dirname(gtfs_path), 'gtfs_corrigido.zip')
            with ZipFile(out_path, 'w', zipfile.ZIP_DEFLATED) as zout:
                for name in names:
                    if name == 'calendar_dates.txt':
                        continue  # substituído pelo calendar.txt sintetizado
                    zout.writestr(name, zin.read(name))
                zout.writestr('calendar.txt', calendar_txt)

        iface.messageBar().pushMessage(
            "Info",
            "calendar.txt gerado a partir de calendar_dates.txt. "
            "Utilize o arquivo 'gtfs_corrigido.zip'.",
            level=Qgis.Info, duration=10)

    @staticmethod
    def _calendar_from_dates(text_stream):
        """Gera o conteúdo de calendar.txt a partir de calendar_dates.txt.

        calendar_dates.txt lista, por service_id, datas com exception_type=1
        (serviço adicionado) ou =2 (serviço removido). Para cada service_id,
        deduzimos quais dias da semana operam — a partir das datas com
        exception_type=1 — e o intervalo [start_date, end_date], produzindo o
        serviço semanal regular exigido por calendar.txt.

        Observação: é uma aproximação. O padrão semanal é reconstruído das
        datas explicitamente atendidas; feeds com operação irregular podem
        não ser representados fielmente por um calendar.txt semanal.
        """
        weekdays = ['monday', 'tuesday', 'wednesday', 'thursday',
                    'friday', 'saturday', 'sunday']
        services = {}  # service_id -> {'days': set(0..6), 'min': str, 'max': str}

        reader = csv.DictReader(text_stream)
        for row in reader:
            # Tolera espaços e BOM nos cabeçalhos/valores
            row = {(k or '').strip(): (v or '').strip() for k, v in row.items()}
            if row.get('exception_type') != '1':
                continue  # só datas adicionadas definem operação regular
            sid = row.get('service_id')
            date = row.get('date')
            if not sid or not date:
                continue
            weekday = datetime.strptime(date, '%Y%m%d').weekday()  # 0=seg .. 6=dom
            svc = services.setdefault(
                sid, {'days': set(), 'min': date, 'max': date})
            svc['days'].add(weekday)
            svc['min'] = min(svc['min'], date)
            svc['max'] = max(svc['max'], date)

        header = 'service_id,' + ','.join(weekdays) + ',start_date,end_date'
        lines = [header]
        for sid, svc in services.items():
            flags = ['1' if i in svc['days'] else '0' for i in range(7)]
            lines.append(','.join([sid] + flags + [svc['min'], svc['max']]))
        return '\n'.join(lines) + '\n'

    def dataClicked(self):
        """Carrega o CSV de demanda num GeoPackage (sigt.gpkg) em segundo
        plano. A ligação com o GTFS é feita por LINHA (route_short_name),
        sem campo derivado."""
        data_path = self.data_widget.filePath()
        if not data_path or not os.path.isfile(data_path):
            iface.messageBar().pushMessage(
                "Erro", "Selecione um arquivo CSV de demanda válido.",
                level=Qgis.Critical, duration=10)
            return

        gpkg_path = os.path.join(os.path.dirname(data_path), 'sigt.gpkg')
        self._demand_task = _DemandLoadTask(data_path, gpkg_path)
        QgsApplication.taskManager().addTask(self._demand_task)
        iface.messageBar().pushMessage(
            "Info",
            "Carregando dados de demanda em segundo plano… acompanhe o "
            "Gerenciador de Tarefas do QGIS.",
            level=Qgis.Info, duration=8)



    def _resolve_gpkg(self, prompt_if_missing=False):
        """Localiza o GeoPackage do GTFS por quatro estratégias em cascata.

        1. self._gpkg_path — memória da sessão atual.
        2. Propriedade 'gpkg_path' do QgsProject — persiste no .qgs/.qgz.
        3. Inferência a partir das camadas GTFS já no projeto: extrai o
           caminho do source() da primeira camada encontrada, resolvendo
           caminhos relativos contra o diretório do projeto.
        4. Diálogo de arquivo (só quando prompt_if_missing=True).

        Retorna o caminho absoluto do .gpkg, ou None se não encontrado."""
        # 1. Instância
        gpkg = getattr(self, '_gpkg_path', None)
        if gpkg and os.path.isfile(gpkg):
            return gpkg

        # 2. Propriedade do projeto
        gpkg = QgsProject.instance().readEntry('SIG-Bus', 'gpkg_path', '')[0]
        if gpkg and os.path.isfile(gpkg):
            self._gpkg_path = gpkg
            return gpkg

        # 3. Inferência — source() de camadas GTFS já carregadas
        project_home = QgsProject.instance().homePath()
        for name in ESSENTIAL_LAYERS:
            layers = QgsProject.instance().mapLayersByName(name)
            if not layers:
                continue
            # source() para OGR/GPKG: "/caminho/feed.gpkg|layername=stops"
            # Com caminhos relativos: "feed.gpkg|layername=stops"
            candidate = layers[0].source().split('|')[0].strip()
            if not os.path.isabs(candidate) and project_home:
                candidate = os.path.join(project_home, candidate)
            if candidate and os.path.isfile(candidate):
                self._gpkg_path = candidate
                QgsProject.instance().writeEntry(
                    'SIG-Bus', 'gpkg_path', candidate)
                return candidate

        if not prompt_if_missing:
            return None

        # 4. Diálogo de arquivo — usuário aponta o .gpkg manualmente
        from qgis.PyQt.QtWidgets import QFileDialog
        start_dir = project_home or os.path.expanduser('~')
        gpkg, _ = QFileDialog.getOpenFileName(
            self, 'Selecione o GeoPackage do GTFS', start_dir,
            'GeoPackage (*.gpkg)')
        if not gpkg:
            return None
        self._gpkg_path = gpkg
        QgsProject.instance().writeEntry('SIG-Bus', 'gpkg_path', gpkg)
        return gpkg

    def _resolve_demand_gpkg(self, gtfs_gpkg):
        """Localiza o GeoPackage que contém dados_demanda.

        Tenta em ordem:
        1. Camada 'dados_demanda' já no projeto → extrai o caminho do source().
        2. sigt.gpkg ao lado do CSV selecionado no data_widget.
        3. O próprio GTFS GeoPackage (caso demanda e GTFS compartilhem o arquivo)."""
        project_home = QgsProject.instance().homePath()

        # 1. Projeto — source() da camada dados_demanda
        for lyr in QgsProject.instance().mapLayersByName('dados_demanda'):
            src = lyr.source().split('|')[0].strip()
            if not os.path.isabs(src) and project_home:
                src = os.path.join(project_home, src)
            if os.path.isfile(src):
                return src

        # 2. Ao lado do CSV
        csv_path = self.data_widget.filePath()
        if csv_path:
            candidate = os.path.join(os.path.dirname(csv_path), 'sigt.gpkg')
            if os.path.isfile(candidate):
                return candidate

        # 3. Mesmo arquivo do GTFS
        if gtfs_gpkg and os.path.isfile(gtfs_gpkg):
            try:
                with sqlite3.connect(gtfs_gpkg) as c:
                    tbls = {r[0] for r in c.execute(
                        "SELECT name FROM sqlite_master WHERE type='table'")}
                if 'dados_demanda' in tbls:
                    return gtfs_gpkg
            except sqlite3.Error:
                pass

        return None

    def reconnectGpkg(self):
        """Reconecta o GeoPackage do GTFS e readiciona as camadas ao projeto.

        Útil quando o QGIS foi fechado e reaberto. Usa _resolve_gpkg() para
        encontrar o arquivo; se nenhuma estratégia automática funcionar, abre
        um diálogo para o usuário apontar o .gpkg manualmente."""
        gpkg = self._resolve_gpkg(prompt_if_missing=True)
        if not gpkg:
            return  # usuário cancelou o diálogo

        project = QgsProject.instance()
        added = []

        # Adiciona camadas essenciais ausentes do projeto (sem duplicar)
        for name in ESSENTIAL_LAYERS:
            if project.mapLayersByName(name):
                continue
            layer = QgsVectorLayer(gpkg + '|layername=' + name, name, 'ogr')
            if layer.isValid():
                project.addMapLayer(layer)
                added.append(name)

        msg = "GeoPackage reconectado ({}).".format(os.path.basename(gpkg))
        if added:
            msg += " Camadas readicionadas: {}.".format(', '.join(added))
        msg += " Use 'Filtrar dados' para carregar os horários da linha."
        iface.messageBar().pushMessage("Info", msg, level=Qgis.Info, duration=12)

    def alocacaoClicked(self):
        """Aloca os embarques do CSV de demanda nos tramos da linha selecionada.

        Requer: linha filtrada (mFeaturePickerWidget), CSV de demanda
        selecionado em 'data_widget' e GeoPackage do GTFS acessível."""
        field = self.mFieldComboBox.currentField()
        feature = self.mFeaturePickerWidget.feature()
        if not feature.isValid() or not field:
            iface.messageBar().pushMessage(
                "Aviso", "Escolha uma linha antes de alocar a demanda.",
                level=Qgis.Warning, duration=8)
            return
        value = feature[field]
        if value is None:
            return

        gpkg = self._resolve_gpkg()
        if not gpkg:
            iface.messageBar().pushMessage(
                "Aviso",
                "GeoPackage não encontrado. Use 'Reconectar GeoPackage' "
                "para localizá-lo.",
                level=Qgis.Warning, duration=8)
            return

        # Localiza onde dados_demanda foi gravado (pode ser sigt.gpkg separado)
        demand_gpkg = self._resolve_demand_gpkg(gpkg)
        if not demand_gpkg:
            iface.messageBar().pushMessage(
                "Aviso",
                "Dados de demanda não encontrados. Use 'Inserir' para "
                "carregá-los antes de alocar.",
                level=Qgis.Warning, duration=8)
            return

        hora_text = self.combo_hora.currentText()
        hora = None if hora_text == 'Total geral' else int(hora_text.replace('h', ''))

        self._alocacao_task = _AlocacaoTask(
            gpkg, str(value), hora=hora, demand_gpkg=demand_gpkg)
        QgsApplication.taskManager().addTask(self._alocacao_task)
        iface.messageBar().pushMessage(
            "Info",
            "Alocando demanda para a linha {} ({}) em segundo plano…".format(
                value, hora_text),
            level=Qgis.Info, duration=6)

    def loadGtfs(self):
        """Carrega o GTFS selecionado num GeoPackage e adiciona as camadas
        ao projeto, usando o leitor embutido (gtfs_reader.py).

        Substitui a antiga integração com o plugin externo GTFS Loader:
        não instala nem invoca outro plugin. Se houver 'gtfs_corrigido.zip'
        (gerado por 'Verificar GTFS'), ele é preferido."""
        gtfs_path = self.gtfs_widget.filePath()
        if not gtfs_path or not os.path.isfile(gtfs_path):
            iface.messageBar().pushMessage(
                "Erro", "Selecione um arquivo GTFS (.zip) válido.",
                level=Qgis.Critical, duration=10)
            return

        # Prefere o feed corrigido, se existir ao lado do original.
        corrigido = os.path.join(os.path.dirname(gtfs_path), 'gtfs_corrigido.zip')
        if os.path.isfile(corrigido):
            gtfs_path = corrigido

        gpkg_path = os.path.splitext(gtfs_path)[0] + '.gpkg'
        # Guardado para o filtro reconstruir a camada virtual por linha.
        # Também persiste nas propriedades do projeto para sobreviver ao
        # fechamento/reabertura do QGIS (reconnectGpkg lê daqui).
        self._gpkg_path = gpkg_path
        QgsProject.instance().writeEntry('SIG-Bus', 'gpkg_path', gpkg_path)

        # O GTFS pode ser grande (stop_times.txt costuma ter dezenas/centenas
        # de MB), então a gravação roda numa tarefa de fundo para não congelar
        # a interface do QGIS. As camadas são adicionadas ao projeto no
        # callback finished(), que executa na thread principal.
        self._load_task = _GtfsLoadTask(gtfs_path, gpkg_path)
        QgsApplication.taskManager().addTask(self._load_task)
        iface.messageBar().pushMessage(
            "Info",
            "Carregando GTFS em segundo plano… acompanhe o Gerenciador de "
            "Tarefas do QGIS.",
            level=Qgis.Info, duration=8)