# -*- coding: utf-8 -*-
"""
/***************************************************************************
 tpu
                                 A QGIS plugin
 Complemento Projeto de Pesquisa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-12
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Diego Camargo
        email                : diegocamargo.bft@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis._core import QgsProject, QgsVectorLayer
from qgis._gui import QgsMapCanvas
from qgis.utils import active_plugins
from qgis.core import Qgis
import pandas as pd
import re

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .TPU_dialog import tpuDialog

import os.path


class TPU:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'tpu_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&113-2021')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('tpu', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/TPU/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'TPU'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&113-2021'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""
        listplugins = [active_plugins]
        search_gtfs = 'GTFS_Loader'
        find = 'no'
        for i in listplugins:
            if search_gtfs in i:
                find = 'yes'
                break
        if find=='yes':
            pass
        else:
            self.iface.messageBar().pushMessage("Você deve instalar o GTFS Loader", level=Qgis.Critical)
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = tpuDialog()
            self.dlg.gtfs_widget.setFilter("ZipeFile (*.zip)")
            self.dlg.data_widget.setFilter("CSV (*.csv)")

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:

            def search(lista, valor):
                return [(lista.index(x)) for x in lista if valor in x]

            registry = QgsProject.instance()
            mapcanvas = QgsMapCanvas()
            names = [layer.name() for layer in QgsProject.instance().mapLayers().values()]
            layer_path = [layer.source() for layer in registry.mapLayers().values()]
            demanda_path = layer_path[search(names, 'dados_demanda')[0]]
            route_path = layer_path[search(names, 'route')[0]]
            pontos = QgsVectorLayer(demanda_path,'dados_demanda','ogr')
            linhas = QgsVectorLayer(route_path,'linhas','ogr')
            for feature in pontos.getFeatures() == 1:
                exp = ' "LINHA"= {0} AND "SUBLINHA"={1} AND "PC"={2}'.format(feature["LINHA"], feature["SUBLINHA"],
                                                                             feature["PC"])
                linha_id = feature["LINHA"]+' '+0+feature["SUBLINHA"]
                exp2 = ' "route_id"={0} '
                pontos.selectByExpression(exp)
                linhas.selectByExpression()


            '''
            demanda_path = re.findall('file:///(.*)\?', csv_path)[0]
            df = pd.read_csv(demanda_path, delimiter=';', encoding='Windows-1252')

            df.loc[df['PC'] == 1, 'I/D'] = 'I'
            df.fillna('V', inplace=True)
            df['indet'] = df['LINHA'].map(str) + '-' + '0' + df['SUBLINHA'].map(str) + df['I/D'].map(str)
            print(df.loc[df['LINHA'] == '1505'])'''
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

