# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TPU_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("GTFS")
        Dialog.resize(556, 280)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(200, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gtfs_widget = QgsFileWidget(Dialog)
        self.gtfs_widget.setGeometry(QtCore.QRect(20, 40, 481, 31))
        self.gtfs_widget.setObjectName("gtfs_widget")
        self.gtfs_label = QtWidgets.QLabel(Dialog)
        self.gtfs_label.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.gtfs_label.setObjectName("gtfs_label")
        self.gtfs_insert_button = QtWidgets.QPushButton(Dialog)
        self.gtfs_insert_button.setGeometry(QtCore.QRect(430, 80, 75, 23))
        self.gtfs_insert_button.setObjectName("gtfs_insert_button")
        self.route_widget = QgsFileWidget(Dialog)
        self.route_widget.setGeometry(QtCore.QRect(20, 150, 481, 31))
        self.route_widget.setObjectName("route_widget")
        self.route_label = QtWidgets.QLabel(Dialog)
        self.route_label.setGeometry(QtCore.QRect(20, 120, 171, 21))
        self.route_label.setObjectName("route_label")
        self.route_insert_button = QtWidgets.QPushButton(Dialog)
        self.route_insert_button.setGeometry(QtCore.QRect(430, 190, 75, 23))
        self.route_insert_button.setObjectName("route_insert_button")
        self.help_button = QtWidgets.QPushButton(Dialog)
        self.help_button.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.help_button.setObjectName("help_button")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gtfs_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Arquivo GTFS (zip)</span></p></body></html>"))
        self.gtfs_insert_button.setText(_translate("Dialog", "Inserir"))
        self.route_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Arquivo rotas </span></p></body></html>"))
        self.route_insert_button.setText(_translate("Dialog", "Inserir"))
        self.help_button.setText(_translate("Dialog", "Ajuda"))
from qgsfilewidget import QgsFileWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
